// Curated icon + emoji sets for the note icon picker, each tagged with keywords
// for the search bar. Icons render the matching lucide-svelte component; emojis
// render the raw character. Note.icon stores either the emoji char or
// `lucide:<Name>`.

import {
	StickyNote,
	FileText,
	ListTodo,
	CheckSquare,
	LayoutDashboard,
	Lightbulb,
	Rocket,
	Target,
	Flag,
	Star,
	Heart,
	Bookmark,
	Bell,
	Calendar,
	Clock,
	Briefcase,
	GraduationCap,
	Code,
	Bug,
	Wrench,
	Beaker,
	Palette,
	Camera,
	Music,
	Film,
	BookOpen,
	PenTool,
	Mail,
	MessageSquare,
	Phone,
	Users,
	User,
	DollarSign,
	ShoppingCart,
	Plane,
	Home,
	Coffee,
	Utensils,
	Dumbbell,
	Leaf,
	Globe,
	MapPin,
	Zap,
	Flame,
	Cloud,
	Sun,
	Moon,
	Trophy,
	Gift
} from 'lucide-svelte';

// All lucide-svelte icons share this component type.
export type IconComp = typeof StickyNote;

export interface IconEntry {
	name: string;
	comp: IconComp;
	keywords: string;
}

export const ICON_SET: IconEntry[] = [
	{ name: 'StickyNote', comp: StickyNote, keywords: 'note sticky memo' },
	{ name: 'FileText', comp: FileText, keywords: 'document file text doc' },
	{ name: 'ListTodo', comp: ListTodo, keywords: 'todo list tasks checklist' },
	{ name: 'CheckSquare', comp: CheckSquare, keywords: 'check done task complete' },
	{ name: 'LayoutDashboard', comp: LayoutDashboard, keywords: 'board dashboard easel grid' },
	{ name: 'Lightbulb', comp: Lightbulb, keywords: 'idea light bulb brainstorm' },
	{ name: 'Rocket', comp: Rocket, keywords: 'rocket launch ship startup' },
	{ name: 'Target', comp: Target, keywords: 'target goal aim objective' },
	{ name: 'Flag', comp: Flag, keywords: 'flag milestone mark' },
	{ name: 'Star', comp: Star, keywords: 'star favorite important' },
	{ name: 'Heart', comp: Heart, keywords: 'heart love like' },
	{ name: 'Bookmark', comp: Bookmark, keywords: 'bookmark save tag' },
	{ name: 'Bell', comp: Bell, keywords: 'bell reminder alert notify' },
	{ name: 'Calendar', comp: Calendar, keywords: 'calendar date schedule event' },
	{ name: 'Clock', comp: Clock, keywords: 'clock time deadline' },
	{ name: 'Briefcase', comp: Briefcase, keywords: 'work briefcase job business' },
	{ name: 'GraduationCap', comp: GraduationCap, keywords: 'study school learn education' },
	{ name: 'Code', comp: Code, keywords: 'code dev programming' },
	{ name: 'Bug', comp: Bug, keywords: 'bug issue defect' },
	{ name: 'Wrench', comp: Wrench, keywords: 'fix tool wrench maintenance' },
	{ name: 'Beaker', comp: Beaker, keywords: 'science experiment lab research' },
	{ name: 'Palette', comp: Palette, keywords: 'design art palette color' },
	{ name: 'Camera', comp: Camera, keywords: 'camera photo picture' },
	{ name: 'Music', comp: Music, keywords: 'music song audio' },
	{ name: 'Film', comp: Film, keywords: 'film movie video' },
	{ name: 'BookOpen', comp: BookOpen, keywords: 'book read reading notes' },
	{ name: 'PenTool', comp: PenTool, keywords: 'pen write draw design' },
	{ name: 'Mail', comp: Mail, keywords: 'mail email message' },
	{ name: 'MessageSquare', comp: MessageSquare, keywords: 'chat message comment talk' },
	{ name: 'Phone', comp: Phone, keywords: 'phone call contact' },
	{ name: 'Users', comp: Users, keywords: 'team people users meeting group' },
	{ name: 'User', comp: User, keywords: 'person user profile' },
	{ name: 'DollarSign', comp: DollarSign, keywords: 'money finance dollar budget' },
	{ name: 'ShoppingCart', comp: ShoppingCart, keywords: 'shopping cart buy groceries' },
	{ name: 'Plane', comp: Plane, keywords: 'travel plane trip flight' },
	{ name: 'Home', comp: Home, keywords: 'home house personal' },
	{ name: 'Coffee', comp: Coffee, keywords: 'coffee break cafe' },
	{ name: 'Utensils', comp: Utensils, keywords: 'food eat restaurant recipe' },
	{ name: 'Dumbbell', comp: Dumbbell, keywords: 'gym fitness workout exercise' },
	{ name: 'Leaf', comp: Leaf, keywords: 'nature plant leaf eco' },
	{ name: 'Globe', comp: Globe, keywords: 'world globe web internet' },
	{ name: 'MapPin', comp: MapPin, keywords: 'location map pin place' },
	{ name: 'Zap', comp: Zap, keywords: 'energy zap fast power' },
	{ name: 'Flame', comp: Flame, keywords: 'fire flame hot urgent' },
	{ name: 'Cloud', comp: Cloud, keywords: 'cloud weather storage' },
	{ name: 'Sun', comp: Sun, keywords: 'sun day light weather' },
	{ name: 'Moon', comp: Moon, keywords: 'moon night dark sleep' },
	{ name: 'Trophy', comp: Trophy, keywords: 'trophy win award achievement' },
	{ name: 'Gift', comp: Gift, keywords: 'gift present birthday' }
];

const iconByName = new Map(ICON_SET.map((e) => [e.name, e]));
export function iconComp(name: string): IconComp | null {
	return iconByName.get(name)?.comp ?? null;
}

export interface EmojiEntry {
	char: string;
	keywords: string;
}

export const EMOJI_SET: EmojiEntry[] = [
	{ char: '📝', keywords: 'note memo write' },
	{ char: '📄', keywords: 'document page file' },
	{ char: '📋', keywords: 'clipboard list tasks' },
	{ char: '✅', keywords: 'check done complete task' },
	{ char: '☑️', keywords: 'checkbox todo check' },
	{ char: '📌', keywords: 'pin important' },
	{ char: '📎', keywords: 'clip attach' },
	{ char: '🗂️', keywords: 'folder organize files' },
	{ char: '📁', keywords: 'folder directory' },
	{ char: '💡', keywords: 'idea light bulb brainstorm' },
	{ char: '🚀', keywords: 'rocket launch ship startup' },
	{ char: '🎯', keywords: 'target goal aim' },
	{ char: '🏁', keywords: 'flag finish milestone' },
	{ char: '⭐', keywords: 'star favorite important' },
	{ char: '❤️', keywords: 'heart love' },
	{ char: '🔥', keywords: 'fire hot urgent trending' },
	{ char: '⚡', keywords: 'energy fast power zap' },
	{ char: '✨', keywords: 'sparkle magic polish new' },
	{ char: '🎉', keywords: 'party celebrate done win' },
	{ char: '🏆', keywords: 'trophy win award' },
	{ char: '📅', keywords: 'calendar date schedule' },
	{ char: '⏰', keywords: 'clock time alarm deadline' },
	{ char: '🔔', keywords: 'bell reminder notify' },
	{ char: '💼', keywords: 'work briefcase business job' },
	{ char: '👥', keywords: 'team people meeting group' },
	{ char: '🧑‍💻', keywords: 'dev coder programmer work' },
	{ char: '💻', keywords: 'computer laptop code' },
	{ char: '🐛', keywords: 'bug issue defect' },
	{ char: '🔧', keywords: 'fix tool wrench' },
	{ char: '🧪', keywords: 'science experiment lab research' },
	{ char: '🎨', keywords: 'art design palette' },
	{ char: '📷', keywords: 'camera photo' },
	{ char: '🎵', keywords: 'music song' },
	{ char: '🎬', keywords: 'film movie video' },
	{ char: '📚', keywords: 'books read study learning' },
	{ char: '✏️', keywords: 'pencil write edit' },
	{ char: '📧', keywords: 'email mail message' },
	{ char: '💬', keywords: 'chat message comment' },
	{ char: '📞', keywords: 'phone call' },
	{ char: '💰', keywords: 'money finance budget' },
	{ char: '🛒', keywords: 'shopping cart groceries buy' },
	{ char: '✈️', keywords: 'travel plane trip flight' },
	{ char: '🏠', keywords: 'home house personal' },
	{ char: '☕', keywords: 'coffee break' },
	{ char: '🍽️', keywords: 'food eat restaurant recipe' },
	{ char: '🏋️', keywords: 'gym fitness workout' },
	{ char: '🌱', keywords: 'plant nature grow eco' },
	{ char: '🌍', keywords: 'world globe earth' },
	{ char: '📍', keywords: 'location pin map place' },
	{ char: '☀️', keywords: 'sun day weather' },
	{ char: '🌙', keywords: 'moon night sleep' },
	{ char: '🎁', keywords: 'gift present birthday' },
	{ char: '⚠️', keywords: 'warning caution alert' },
	{ char: '❓', keywords: 'question help unknown' },
	{ char: '🔒', keywords: 'lock secure private' },
	{ char: '🧠', keywords: 'brain think mind idea' }
];
