<script lang="ts">
  import { Button } from '$lib/components/ui';
  import { onMount } from 'svelte';

  let { disclosure = 'Generated by AI' }: { disclosure?: string } = $props();

  const SESSION_KEY = 'minion-ai-disclosure-collapsed';

  let collapsed = $state(false);

  // Load collapse state from sessionStorage on mount
  onMount(() => {
    try {
      const stored = sessionStorage.getItem(SESSION_KEY);
      collapsed = stored === '1';
    } catch {
      // sessionStorage unavailable — stay expanded
    }
  });

  function toggle() {
    collapsed = !collapsed;
    try {
      if (collapsed) {
        sessionStorage.setItem(SESSION_KEY, '1');
      } else {
        sessionStorage.removeItem(SESSION_KEY);
      }
    } catch {
      // sessionStorage unavailable — toggle works in-memory only
    }
  }
</script>

<span
  class="ai-disclosure inline-flex items-center gap-1 text-[length:var(--font-size-telemetry)] text-muted-strong select-none"
  role="status"
  aria-label={disclosure}
>
  {#if !collapsed}
    <span class="ai-disclosure__text tracking-wide">
      {disclosure}
    </span>
  {/if}
  <Button
    variant="ghost"
    type="button"
    class="ai-disclosure__toggle w-3 h-3 flex items-center justify-center rounded-sm
      hover:bg-accent/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent
      transition-all duration-[var(--duration-fast)]"
    title={collapsed ? 'Show AI disclosure' : 'Collapse AI disclosure'}
    aria-label={collapsed ? 'Show AI disclosure' : 'Collapse AI disclosure'}
    aria-expanded={!collapsed}
    onclick={toggle}
  >
    <span class="text-[length:var(--font-size-telemetry)] leading-none" aria-hidden="true">
      {collapsed ? '●' : '○'}
    </span>
  </Button>
</span>

<style>
  .ai-disclosure {
    opacity: 0.8;
  }

  .ai-disclosure:hover {
    opacity: 1;
  }

  :global(.ai-disclosure__toggle) {
    opacity: 0.7;
  }

  :global(.ai-disclosure__toggle:hover) {
    opacity: 1;
  }

  /* Touch devices: always show toggle */
  @media (hover: none) {
    :global(.ai-disclosure__toggle) {
      opacity: 1;
    }
  }
</style>
