<script lang="ts">
  import { onMount } from 'svelte';

  let { disclosure = 'Generated by AI' }: { disclosure?: string } = $props();

  const SESSION_KEY = 'minion-ai-disclosure-collapsed';

  let collapsed = $state(false);

  // Load collapse state from sessionStorage on mount
  onMount(() => {
    try {
      const stored = sessionStorage.getItem(SESSION_KEY);
      collapsed = stored === '1';
    } catch {
      // sessionStorage unavailable — stay expanded
    }
  });

  function toggle() {
    collapsed = !collapsed;
    try {
      if (collapsed) {
        sessionStorage.setItem(SESSION_KEY, '1');
      } else {
        sessionStorage.removeItem(SESSION_KEY);
      }
    } catch {
      // sessionStorage unavailable — toggle works in-memory only
    }
  }
</script>

<span
  class="ai-disclosure inline-flex items-center gap-1 text-[9px] text-muted-foreground/70 select-none"
  role="status"
  aria-label={disclosure}
>
  {#if !collapsed}
    <span class="ai-disclosure__text tracking-wide">
      {disclosure}
    </span>
  {/if}
  <button
    type="button"
    class="ai-disclosure__toggle w-3 h-3 flex items-center justify-center rounded-sm
      hover:bg-accent/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent
      transition-all duration-150"
    title={collapsed ? 'Show AI disclosure' : 'Collapse AI disclosure'}
    aria-label={collapsed ? 'Show AI disclosure' : 'Collapse AI disclosure'}
    aria-expanded={!collapsed}
    onclick={toggle}
  >
    <span class="text-[6px] leading-none" aria-hidden="true">
      {collapsed ? '●' : '○'}
    </span>
  </button>
</span>

<style>
  .ai-disclosure {
    opacity: 0.8;
  }

  .ai-disclosure:hover {
    opacity: 1;
  }

  .ai-disclosure__toggle {
    opacity: 0.7;
  }

  .ai-disclosure__toggle:hover {
    opacity: 1;
  }

  /* Touch devices: always show toggle */
  @media (hover: none) {
    .ai-disclosure__toggle {
      opacity: 1;
    }
  }
</style>
