#!/usr/bin/env bun
/**
 * Builds .env.qa (gitignored, mode 600) — the env file docker-compose.qa.yml
 * loads for the app container — from the running local Supabase stack
 * (`supabase status -o env`) plus the static QA defaults from spec §2.
 *
 * Networking: the app container runs with `network_mode: host`
 * (docker-compose.qa.yml), so it reaches Supabase on the same
 * 127.0.0.1:<port> addresses the browser and this script use. There is no
 * separate in-network hostname to resolve and no server-only Supabase URL
 * var in this codebase (src/lib/supabase/client.ts and src/server/supabase.ts
 * both read PUBLIC_SUPABASE_URL) — one URL works for browser, server and CLI.
 *
 * Usage: bun scripts/qa/env.ts
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseEnvFile } from './snapshot-env';
import { SUPABASE_CLI_SPEC, spawnSupabaseCli } from './supabase-cli';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const QA_DIR = join(ROOT, '.qa');
const ENCRYPTION_KEY_FILE = join(QA_DIR, 'encryption-key');
const OUT_FILE = join(ROOT, '.env.qa');

export interface QaSupabaseStatus {
  apiUrl: string;
  dbUrl: string;
  anonKey: string;
  serviceRoleKey: string;
}

/** Pure: parses `supabase status -o env` stdout (KEY="value" per line). */
export function parseSupabaseStatusEnv(stdout: string): QaSupabaseStatus {
  const vars = parseEnvFile(stdout);
  const required = ['API_URL', 'DB_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY'] as const;
  const missing = required.filter((key) => !vars[key]);
  if (missing.length > 0) {
    throw new Error(
      `supabase status -o env is missing ${missing.join(', ')} — the CLI's env output shape ` +
        `may have changed (pinned to ${SUPABASE_CLI_SPEC})`,
    );
  }
  return {
    apiUrl: vars.API_URL,
    dbUrl: vars.DB_URL,
    anonKey: vars.ANON_KEY,
    serviceRoleKey: vars.SERVICE_ROLE_KEY,
  };
}

/** Pure: builds the .env.qa file body from the parsed status + a stable encryption key. */
export function buildEnvQa(status: QaSupabaseStatus, encryptionKey: string): string {
  const lines = [
    '# Generated by `bun run qa:env` — do not edit by hand, re-run instead.',
    '# Loaded by docker-compose.qa.yml (env_file) for the hub-qa app container.',
    '',
    '# --- Supabase: network_mode: host means one URL for browser + server + CLI ---',
    `PUBLIC_SUPABASE_URL=${status.apiUrl}`,
    `PUBLIC_SUPABASE_ANON_KEY=${status.anonKey}`,
    `SUPABASE_SERVICE_ROLE_KEY=${status.serviceRoleKey}`,
    `SUPABASE_DB_URL=${status.dbUrl}`,
    'AUTH_PROVIDER=supabase',
    'PUBLIC_AUTH_PROVIDER=supabase',
    '',
    '# --- libsql (gateway tables, applied by scripts/qa/hub-entrypoint.sh) ---',
    'TURSO_DB_URL=file:./data/qa/minion_hub.db',
    '',
    '# --- QA stack identity ---',
    'PUBLIC_DEFAULT_ORG_SLUG=faces-sculptors',
    // Stable across `qa:up`/`qa:reset` reruns (see loadOrCreateEncryptionKey
    // below) so rows sealed by a previous run stay decryptable.
    `ENCRYPTION_KEY=${encryptionKey}`,
    'BRAIN_VECTOR_ENABLED=false',
    'BRAIN_ENRICHMENT_ENABLED=false',
    '',
    '# --- Stubs: no outbound network calls are made from the QA stack ---',
    'PUBLIC_POSTHOG_KEY=phc_qa_stack_stub_key',
    'PUBLIC_POSTHOG_HOST=https://us.i.posthog.com',
    '',
    'NODE_OPTIONS=--max-old-space-size=2048',
    '',
  ];
  return lines.join('\n');
}

/** A random key generated once and reused: see the ENCRYPTION_KEY comment above. */
function loadOrCreateEncryptionKey(): string {
  if (existsSync(ENCRYPTION_KEY_FILE)) {
    const existing = readFileSync(ENCRYPTION_KEY_FILE, 'utf8').trim();
    if (existing) return existing;
  }
  mkdirSync(QA_DIR, { recursive: true });
  const key = randomBytes(32).toString('hex');
  writeFileSync(ENCRYPTION_KEY_FILE, key + '\n', { mode: 0o600 });
  return key;
}

async function main(): Promise<void> {
  console.log(`qa:env — reading \`supabase status -o env\` (npx ${SUPABASE_CLI_SPEC})…`);
  const result = spawnSupabaseCli(['status', '-o', 'env'], ROOT, { encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(
      `supabase status failed (is the QA stack running? \`supabase start\` first):\n${result.stderr || result.stdout}`,
    );
  }
  const status = parseSupabaseStatusEnv(result.stdout);
  const encryptionKey = loadOrCreateEncryptionKey();
  const body = buildEnvQa(status, encryptionKey);
  writeFileSync(OUT_FILE, body, { mode: 0o600 });
  chmodSync(OUT_FILE, 0o600);
  console.log(`qa:env — wrote ${OUT_FILE}`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((err) => {
    console.error(`qa:env FAILED — ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
  });
}
