/**
 * Contract test for the QA seed matrix (spec §7 S3 DoD). Skips entirely when
 * `HUB_TEST_DB_URL` is unset — same convention as every other
 * `*.sql.integration.test.ts` in this repo (`src/server/test-utils/test-db-url.ts`).
 *
 * Flow: run the real seed once (idempotent — safe against an already-seeded
 * DB), assert every matrix id resolved to a real row, run a handful of extra
 * state assertions the generic {table,where} check can't express, then prove
 * idempotency by running the seed again and diffing the total row count.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import postgres from 'postgres';
import { createClient as createLibsqlClient, type Client as LibsqlClient } from '@libsql/client';
import { testDatabaseUrl } from '../../../src/server/test-utils/test-db-url';
import { runSeed } from './index';
import { countAllSeededRows, type RowRef } from './db';
import { MATRIX, matrixById } from './matrix';
import { GRANT_HALF_USED, GRANT_EXHAUSTED } from './pos';
import { CHAIN_INVOICE_ID } from './stock';
import { ORG_BUSINESS, userId } from './tenancy';

const dbUrl = testDatabaseUrl();
const MATRIX_BY_ID = matrixById();

describe.skipIf(!dbUrl)('QA seed matrix contract', () => {
  let sql: ReturnType<typeof postgres>;
  let libsql: LibsqlClient;
  let registered: ReadonlyMap<string, RowRef>;

  beforeAll(async () => {
    process.env.SUPABASE_DB_URL ??= dbUrl;
    process.env.PUBLIC_SUPABASE_URL ??= 'http://127.0.0.1:54421';
    // TODO(handoff): SUPABASE_SERVICE_ROLE_KEY is generated by `supabase start`
    // (S1/S2's bootstrap, owned by a concurrent agent in this worktree) and
    // isn't something this test can fabricate — export it before running
    // `bun run qa:seed:verify`, or this suite fails fast with a clear message
    // instead of a confusing GoTrue 401.
    if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('SUPABASE_SERVICE_ROLE_KEY is required to run the QA seed contract test.');
    }
    const result = await runSeed();
    registered = result.registered;
    expect(
      result.missing,
      `matrix ids never registered by a seed module: ${result.missing.join(', ')}`,
    ).toEqual([]);
    sql = postgres(dbUrl!, { prepare: false, max: 3 });
    libsql = createLibsqlClient({
      url: process.env.TURSO_DB_URL ?? 'file:./data/qa/minion_hub.db',
      authToken: process.env.TURSO_DB_AUTH_TOKEN,
    });
  }, 120_000);

  afterAll(async () => {
    await sql?.end({ timeout: 5 });
    libsql?.close();
  });

  function ident(name: string): string {
    if (!/^[a-z_][a-z0-9_]*$/i.test(name)) throw new Error(`unsafe identifier: ${name}`);
    return `"${name}"`;
  }

  /** `gateway.*` ids live in libsql, not Postgres — Postgres even has an
   *  UNRELATED table also named `sessions` (@minion-stack/db/pg/schema),
   *  so routing on the matrix entry's domain (not the table name) is the
   *  only way to avoid silently querying the wrong database. */
  async function rowExists(matrixId: string, ref: RowRef): Promise<boolean> {
    const keys = Object.keys(ref.where);
    const isGateway = MATRIX_BY_ID.get(matrixId)?.domain === 'gateway';
    if (isGateway) {
      const conditions = keys.map((k) => `${ident(k)} = ?`).join(' and ');
      const values = keys.map((k) => ref.where[k]);
      const result = await libsql.execute({
        sql: `select 1 as x from ${ident(ref.table)} where ${conditions} limit 1`,
        args: values as (string | number | boolean | null)[],
      });
      return result.rows.length > 0;
    }
    const conditions = keys.map((k, i) => `${ident(k)} = $${i + 1}`).join(' and ');
    const values = keys.map((k) => ref.where[k]);
    const rows = await sql.unsafe<{ x: number }[]>(
      `select 1 as x from ${ident(ref.table)} where ${conditions} limit 1`,
      values,
    );
    return rows.length > 0;
  }

  it.each(MATRIX.map((entry) => [entry.id, entry.why] as const))('%s — %s', async (matrixId) => {
    const ref = registered.get(matrixId);
    expect(ref, `${matrixId} was never registered by a seed module`).toBeDefined();
    const exists = await rowExists(matrixId, ref!);
    if (ref!.expect === 'absent') {
      expect(
        exists,
        `${matrixId}: expected NO row matching ${ref!.table} ${JSON.stringify(ref!.where)}, but one exists`,
      ).toBe(false);
    } else {
      expect(
        exists,
        `${matrixId}: no row matches ${ref!.table} ${JSON.stringify(ref!.where)}`,
      ).toBe(true);
    }
  });

  it('pos.grant.half-used has exactly 4 live redemptions of 6 (incl. sched.booking.fully-linked)', async () => {
    const [row] = await sql<{ live: number; total: number }[]>`
      select
        (select count(*)::int from pos_package_redemptions where grant_id = ${GRANT_HALF_USED} and reversed_at is null) as live,
        (select sessions_total from pos_package_grants where id = ${GRANT_HALF_USED}) as total
    `;
    expect(row.live).toBe(4);
    expect(row.total).toBe(6);
  });

  it('pos.grant.exhausted has live redemptions equal to sessions_total', async () => {
    const [row] = await sql<{ live: number; total: number }[]>`
      select
        (select count(*)::int from pos_package_redemptions where grant_id = ${GRANT_EXHAUSTED} and reversed_at is null) as live,
        (select sessions_total from pos_package_grants where id = ${GRANT_EXHAUSTED}) as total
    `;
    expect(row.live).toBe(row.total);
  });

  it('tenancy.user.legacy-member has organization_members but no member_roles row', async () => {
    const legacyMemberId = userId('tenancy.user.legacy-member');
    const [membership] = await sql<{ n: number }[]>`
      select count(*)::int as n from organization_members where organization_id = ${ORG_BUSINESS} and profile_id = ${legacyMemberId}
    `;
    const [roles] = await sql<{ n: number }[]>`
      select count(*)::int as n from member_roles where org_id = ${ORG_BUSINESS} and profile_id = ${legacyMemberId}
    `;
    expect(membership.n).toBe(1);
    expect(roles.n).toBe(0);
  });

  it('att.file.near-quota sits within 1% under orgQuotaBytes', async () => {
    const quota = Number(process.env.ATTACHMENT_ORG_QUOTA_BYTES) || 2 * 1024 * 1024 * 1024;
    const ref = registered.get('att.file.near-quota')!;
    // postgres.js returns bigint columns as strings to avoid precision loss.
    const [row] = await sql<
      { size_bytes: string }[]
    >`select size_bytes from files where id = ${ref.where.id as string}`;
    const sizeBytes = Number(row.size_bytes);
    expect(sizeBytes).toBeLessThan(quota);
    expect(sizeBytes).toBeGreaterThan(quota * 0.99);
  });

  it('stock.entry.issue-duplicate-invoice-id: a case/space variant of the same invoiceId is rejected', async () => {
    const duplicateEntryId = '00000000-0000-4000-8000-0000000000fe';
    const attempt = sql`
      insert into stk_entries (id, org_id, human_id, type, status, metadata)
      values (${duplicateEntryId}, ${ORG_BUSINESS}, 'STE-QA-DUP', 'issue', 'draft', ${sql.json({
        invoiceId: `  ${CHAIN_INVOICE_ID.toLowerCase()}  `,
      })})
    `;
    await expect(attempt).rejects.toMatchObject({ code: '23505' });
  });

  it('re-running the seed is idempotent (zero new rows)', async () => {
    const before = await countAllSeededRows(sql);
    const second = await runSeed();
    expect(second.missing).toEqual([]);
    const after = await countAllSeededRows(sql);
    expect(after).toBe(before);
  }, 120_000);
});
