export const NATIVE_POSTGRES_EXCLUDES = [
  '**/*.sql.integration.test.ts',
  'src/server/services/brain-business-persistence.service.test.ts',
  'src/server/services/crm-funnel.concurrent.integration.test.ts',
] as const;

export type NativePostgresLane =
  | 'crm-deposit'
  | 'crm-pagination'
  | 'crm-concurrent'
  | 'jobs'
  | 'attachments'
  | 'principal'
  | 'custom-properties'
  | 'formula'
  | 'qa-native';

export type NativePostgresAdmission = {
  file: string;
  minimumAssertions: number;
  requiredBehaviors: readonly string[];
};

/**
 * Single ownership and semantic evidence manifest for tests excluded from ordinary Vitest.
 * Every current semantic test name is required; the count is a supplementary ratchet.
 */
export const NATIVE_POSTGRES_MANIFEST = {
  'crm-deposit': [
    {
      file: 'src/server/services/crm-deposit-rule.sql.integration.test.ts',
      minimumAssertions: 5,
      requiredBehaviors: [
        'crm-deposit-rule against PostgreSQL isDepositText agrees with depositMatchSql/notDepositMatchSql for every case in the shared table',
        'crm-deposit-rule against PostgreSQL multi-keyword rule: PostgreSQL OR/AND semantics agree with isDepositText for every keyword',
        "crm-deposit-rule against PostgreSQL escapeLikePattern('100%') does not let an operator keyword widen into a wildcard",
        'crm-deposit-rule against PostgreSQL classifies a deposit-worded row and a procedure-worded row on opposite sides of IS_DEPOSIT/IS_PROCEDURE — the predicate crm-finance/crm-journey/crm-similarity share',
        'crm-deposit-rule against PostgreSQL contactFinanceSummary/contactJourney representative-item ORDER BY puts the procedure line before the deposit line at equal price',
      ],
    },
  ],
  'crm-pagination': [
    {
      file: 'src/server/services/crm-contact-activity-rollup.sql.integration.test.ts',
      minimumAssertions: 5,
      requiredBehaviors: [
        'crm_contact_activity_stats migration backfills existing identities and keeps zero-message contacts explicit',
        'crm_contact_activity_stats migration rebuilds history when a message arrived before its identity',
        'crm_contact_activity_stats migration increments new messages, ignores bot rows, and does not double-count duplicate upserts',
        'crm_contact_activity_stats migration tracks distinct channels and rebuilds both sides of identity reassignment/deletion',
        'crm_contact_activity_stats migration matches the authoritative live ledger aggregation field-for-field',
      ],
    },
    {
      file: 'src/server/services/crm-contacts.sql.integration.test.ts',
      minimumAssertions: 19,
      requiredBehaviors: [
        'rankContactsPage against PostgreSQL keeps the independently counted total across populated and empty offsets',
        'rankContactsPage against PostgreSQL sorts ICP null last and traverses tied rows exactly once',
        'rankContactsPage against PostgreSQL matches exact phone/DNI prefix 5198',
        'rankContactsPage against PostgreSQL matches exact phone/DNI prefix 4455',
        'rankContactsPage against PostgreSQL matches exact phone/DNI prefix 9988',
        "rankContactsPage against PostgreSQL sort:'revenue' ranks by the finance bridge and never leaks the helper column",
        'rankContactsPage against PostgreSQL a masked principal cannot probe the phone/DNI/doc_number digits the mask hides 5198',
        'rankContactsPage against PostgreSQL a masked principal cannot probe the phone/DNI/doc_number digits the mask hides 9988',
        'rankContactsPage against PostgreSQL does not match phone/DNI mid-string 8765',
        'rankContactsPage against PostgreSQL does not match phone/DNI mid-string 5566',
        'rankContactsPage against PostgreSQL does not match phone/DNI mid-string 8877',
        'rankContactsPage against PostgreSQL awaitingReply selects exactly the rows the client predicate kept',
        'rankContactsPage against PostgreSQL a bounded acquisition window runs on real Postgres and counts only the cohort',
        'rankContactsPage against PostgreSQL aggregates the full dashboard in SQL with the same roster semantics',
        'rankContactsPage against PostgreSQL buyerOnly selects exactly the contacts with a purchase history',
        "rankContactsPage against PostgreSQL reservedOnly mirrors the list's reserved toggle (finance.reservedOnly), not is_buyer",
        'rankContactsPage against PostgreSQL minIcp/maxIcp are inclusive at both endpoints and drop unscored rows',
        'rankContactsPage against PostgreSQL a same-tenant rule change (default → custom → empty → back to absent) is visible immediately, with finance/contacts classification agreeing at every step',
        'rankContactsPage against PostgreSQL contactFinanceSummary and rankCustomers follow the configured rule: representative item and top product move, invoice arithmetic does not',
      ],
    },
    {
      file: 'src/server/services/crm-funnel-parity.sql.integration.test.ts',
      minimumAssertions: 7,
      requiredBehaviors: [
        'SQL funnel_stage vs the TS funnel helpers does not promote a contact whose only procedure invoice was voided',
        'SQL funnel_stage vs the TS funnel helpers agrees with maxFunnelStage(effectiveFunnelStage, financeFloorStage) on every combination',
        'SQL funnel_stage vs the TS funnel helpers filters funnelStage=lead to exactly the TS-derived set',
        'SQL funnel_stage vs the TS funnel helpers filters funnelStage=opportunity to exactly the TS-derived set',
        'SQL funnel_stage vs the TS funnel helpers filters funnelStage=customer to exactly the TS-derived set',
        'SQL funnel_stage vs the TS funnel helpers filters funnelStage=loyal to exactly the TS-derived set',
        'SQL funnel_stage vs the TS funnel helpers pages a funnel-filtered set without leaking rows from other stages',
      ],
    },
  ],
  'crm-concurrent': [
    {
      file: 'src/server/services/crm-funnel.concurrent.integration.test.ts',
      minimumAssertions: 7,
      requiredBehaviors: [
        'funnel writes against concurrent PostgreSQL transactions an automatic writer waiting on the row lock observes a concurrent manual pin',
        'funnel writes against concurrent PostgreSQL transactions a _funnel write queued behind an open _journey transaction keeps BOTH keys',
        'funnel writes against concurrent PostgreSQL transactions a _funnel write that commits INSIDE the _journey transaction is not reverted by it',
        'funnel writes against concurrent PostgreSQL transactions setFunnelStage and the customFieldsPatch writer (contact patch service) both queue on the coordinator lock and both survive — funnel starts first',
        'funnel writes against concurrent PostgreSQL transactions setFunnelStage and the customFieldsPatch writer both queue on the coordinator lock and both survive — patch starts first (reverse start order)',
        "funnel writes against concurrent PostgreSQL transactions setContactCustomField('_funnel', ...) and setContactCustomField('_relationship', ...) both queue on the coordinator lock and both survive — funnel starts first",
        "funnel writes against concurrent PostgreSQL transactions setContactCustomField('_funnel', ...) and setContactCustomField('_relationship', ...) both queue on the coordinator lock and both survive — relationship starts first (reverse start order)",
      ],
    },
  ],
  jobs: [
    {
      file: 'src/server/services/join/pending.repository.sql.integration.test.ts',
      minimumAssertions: 9,
      requiredBehaviors: [
        'pending join identity on PostgreSQL selects pending identity only for the exact applicant and current target organization',
        'pending join identity on PostgreSQL creates independent org requests and retries only the exact target',
        'pending join identity on PostgreSQL admits one creator across concurrent retries and returns the same receipt',
        'pending join identity on PostgreSQL does not substitute another applicant request in the same organization',
        'pending join identity on PostgreSQL returns explicit zero one and many own pending states without private fields',
        'pending join identity on PostgreSQL reports overflow after fifty requests without selecting an arbitrary organization',
        'pending join identity on PostgreSQL resolved requests neither appear pending nor suppress a new pending request',
        'pending join identity on PostgreSQL orders equal timestamps by id so bounded pages are deterministic',
        'pending join identity on PostgreSQL fails unavailable on database errors and never returns provider or applicant details',
      ],
    },
    {
      file: 'src/server/services/notifications/scheduler.sql.integration.test.ts',
      minimumAssertions: 16,
      requiredBehaviors: [
        'native notification scheduler ownership applies the worker scheduler through the production runner with exact durable roles, marker and no-op replay',
        'native notification scheduler ownership fences global scheduler ownership across standby, heartbeat, expiry, replacement and stale release',
        'native notification scheduler ownership rate bounds durable failed-admission observations and cannot overwrite a live runtime',
        'native notification scheduler ownership fences organization renewal and settlement by live runtime owner and monotonic generation',
        'native notification scheduler ownership restores coordinator role, GUCs and pool state after callback and statement timeout failures',
        'native notification scheduler ownership waits through a held runtime row for heartbeat, organization renewal and completion without reporting lease loss',
        'native notification scheduler ownership enforces exact coordinator and health-reader role, RLS, column and generation boundaries',
        'native notification scheduler ownership alternates pending and expired discovery fairly under the four-claim and sixteen-candidate ceilings',
        'native notification scheduler ownership returns coordinator busy for a held cursor and advances past a separately held organization row',
        'native notification scheduler ownership rolls back pre-aborted discovery and explicitly abandons only an exact unstarted organization claim',
        'native notification scheduler ownership rolls back an in-flight aborted discovery without advancing its cursor or stranding a claim',
        'native notification scheduler ownership reconciles a failed unstarted-claim abandon through exact live receipt expiry before releasing global ownership',
        'native notification scheduler ownership isolates organization health and restores the pooled role and GUCs after success and SQL timeout',
        'native notification scheduler ownership fails closed without repairing missing or unknown-version runtime and cursor singletons',
        'native notification scheduler ownership rejects bigint generation exhaustion for runtime, admission, organization and cursor state without resetting history',
        'native notification scheduler ownership uses bounded production discovery and health SQL plans across one hundred thousand rows and fails when required indexes are removed',
      ],
    },
    {
      file: 'src/server/services/notifications/event-outbox.sql.integration.test.ts',
      minimumAssertions: 14,
      requiredBehaviors: [
        'native notification event outbox ownership applies Slice2 and the event outbox through the production runner with exact roles, catalog and no-op replay',
        'native notification event outbox ownership admits every reviewed catalog producer pair through the append API and rejects a mismatched SQL tuple',
        'native notification event outbox ownership commits source evidence atomically and rolls back explicit, oversize and caught append failures',
        'native notification event outbox ownership converges eight concurrent exact retries, isolates organizations and rejects source or payload digest conflicts',
        'native notification event outbox ownership claims a later-occurring commit first and still observes the earlier-timestamped uncommitted event after it commits',
        'native notification event outbox ownership pages 501 equal-time rows as 250, 250 and 1, reports contention, and reclaims only the crashed generation',
        'native notification event outbox ownership fences expiry and generation independently, stale owners, renewal, deadline drift and terminal replay',
        'native notification event outbox ownership enforces real producer and worker RLS, ACL, trigger origin and role-graph boundaries',
        'native notification event outbox ownership restores the dedicated worker pool after success, application error and typed SQL timeout without using ordinary pools',
        'native notification event outbox ownership leaves future catalogs pending for the old worker and lets an explicitly compatible raw worker claim them',
        'native notification event outbox ownership quarantines malformed supported rows with finite reasons and never returns them as empty successes',
        'native notification event outbox ownership quarantines 250 malformed rows in one bounded batch and atomically rejects invalid, foreign, stale or application tuples',
        'native notification event outbox ownership rejects every over-limit SQL envelope field and multibyte boundary without leaving event or outbox rows',
        'native notification event outbox ownership uses bounded partial-index claim and complement plans over 100000 mixed rows and fails the same gates without each index',
      ],
    },
    {
      file: 'src/server/db/notification-legacy-reconciliation.sql.integration.test.ts',
      minimumAssertions: 10,
      requiredBehaviors: [
        'notification legacy reconciliation against PostgreSQL uses exact frozen historical migration bytes and supported-baseline provenance',
        'notification legacy reconciliation against PostgreSQL runs the production runner from fresh and every exact historical prefix while preserving old values',
        'notification legacy reconciliation against PostgreSQL restores the supported QA baseline and reaches zero pending migrations through the production runner',
        'notification legacy reconciliation against PostgreSQL rejects a premarked but omitted reconciliation as noncanonical migration evidence',
        'notification legacy reconciliation against PostgreSQL rejects altered catalogs and rows transactionally with a bounded conflict',
        'notification legacy reconciliation against PostgreSQL kills classifier, ACL, FORCE-RLS, and transition-trigger source mutants transactionally',
        'notification legacy reconciliation against PostgreSQL rejects a transitive app-ledger membership without mutating the cluster role graph',
        'notification legacy reconciliation against PostgreSQL enforces exact app-ledger ACLs and organization RLS across independent sessions',
        'notification legacy reconciliation against PostgreSQL allows only sending-to-terminal reminder transitions and preserves immutable identity',
        'notification legacy reconciliation against PostgreSQL keeps legacy sent rows as immutable claims without creating delivery effects',
      ],
    },
    {
      file: 'src/server/services/fresh-org-authority.sql.integration.test.ts',
      minimumAssertions: 5,
      requiredBehaviors: [
        'native fresh organization notification authority uses active exact-org membership, auth users destinations and current explicit permission overrides',
        'native fresh organization notification authority suppresses a prepared recipient after verified destination, permission or membership changes',
        'native fresh organization notification authority rejects candidate limit plus one before filtering recipients',
        'native fresh organization notification authority separates current comms create and manage from view-only and legacy administrator roles',
        'native fresh organization notification authority revokes comms authority after membership or active organization removal with no cross-org admin bypass',
      ],
    },
    {
      file: 'src/server/services/pulse-tenant-boundary.sql.integration.test.ts',
      minimumAssertions: 3,
      requiredBehaviors: [
        'native Pulse tenant boundary binds machine identity to route storage and same-org dedupe under actual RLS',
        'native Pulse tenant boundary resolves real server credentials through the hook and rejects browser or incomplete machines before storage',
        'native Pulse tenant boundary enables Pulse RLS for the restricted ledger role without claiming FORCE',
      ],
    },
    {
      file: 'src/server/services/pos-categories.sql.integration.test.ts',
      minimumAssertions: 4,
      requiredBehaviors: [
        'fin_product_categories PostgreSQL invariants backfills distinct exact legacy values without changing product assignments',
        'fin_product_categories PostgreSQL invariants cascades exact-name rename and clears assignments on delete',
        'fin_product_categories PostgreSQL invariants rejects cross-org and stale category assignments',
        'fin_product_categories PostgreSQL invariants forces RLS so an app role sees and changes only its organization',
      ],
    },
    {
      file: 'src/server/services/pos-money.sql.integration.test.ts',
      minimumAssertions: 19,
      requiredBehaviors: [
        'native POS decimal and schedule boundaries persists rounded principal and reconciled dates through the real service and RLS transaction',
        'native POS decimal and schedule boundaries rejects bad dates, subcent rows, oversized and mismatched schedules without inserting a plan',
        'native POS decimal and schedule boundaries rejects principal overflow and unsupported currencies before mutation and preserves absent schedules',
        'native POS decimal and schedule boundaries commits both booking links and rolls back missing, foreign or already funded booking attempts',
        'native POS decimal and schedule boundaries reads only the unpaid instalment remainder and never offers settled or overpaid principal',
        'native POS decimal and schedule boundaries keeps legacy schedule corruption visible without hiding valid balance or changing history',
        'native POS decimal and schedule boundaries conserves signed ledger cents and rejects unsafe new or corrupt stored amounts',
        'native POS decimal and schedule boundaries fences package grant currency by the historical source ticket and organization before writing',
        'native plan operation admission keeps identical requests with distinct operation IDs independent and ignores caller actor overrides',
        'native plan operation admission converges concurrent same-key creates and never exposes request identity in plan DTOs',
        'native plan operation admission settles a keyed plan without exposing request identity through its nested detail projection',
        'native plan operation admission replays the original cancelled plan after settings change without reading settings again',
        'native plan operation admission rejects changed intent and another actor while allowing the same key in another organization',
        'native plan operation admission leaves no receipt after booking-link rollback and permits a later valid retry with that key',
        'native plan operation admission cancellation wins its lock order and fences every delayed create without cancelling other plans',
        'native plan operation admission create wins its lock order and cancellation returns the committed receipt without changing agreement state',
        'native plan operation admission enforces paired key hash actor constraints and per-organization uniqueness in production DDL',
        'native plan operation admission denies browser tombstone access and tenant update delete or cross-organization insert under forced RLS',
        'native plan operation admission requires a canonical authenticated actor for keyed operations while preserving legacy creation',
      ],
    },
    {
      file: 'src/server/services/marketplace/marketplace-operations.sql.integration.test.ts',
      minimumAssertions: 15,
      requiredBehaviors: [
        'native marketplace lease and publication ownership uses distinct backends and denies browser and tenant roles operational-table writes',
        'native marketplace lease and publication ownership rejects partial leases and invalid cursors using database constraints',
        'native marketplace lease and publication ownership allows exactly one simultaneous catalog claimant and a later expired-owner replacement',
        'native marketplace lease and publication ownership rejects an expired catalog publisher without changing catalog or cursor',
        'native marketplace lease and publication ownership rolls back every catalog write if database time expires ownership before final progress CAS',
        'native marketplace lease and publication ownership isolates a permanent row constraint failure while advancing successful siblings as partial',
        'native marketplace lease and publication ownership aborts the whole page on infrastructure errors instead of classifying them as bad metadata',
        'native marketplace lease and publication ownership resumes a multi-page snapshot and keeps final completion distinct from a failed new listing',
        'native marketplace lease and publication ownership recognizes a committed catalog page after its database response is lost',
        'native marketplace lease and publication ownership serializes document claims across backends and rejects an expired file publisher',
        'native marketplace lease and publication ownership invalidates changed metadata without erasing old documents or letting a stale worker overwrite them',
        'native marketplace lease and publication ownership rolls back document fields and loaded marker when lease expires before final publication CAS',
        'native marketplace lease and publication ownership bounds lock contention while preserving the actual lock owner',
        'native marketplace lease and publication ownership invalidates legacy successful markers before treating any historical bundle as installable',
        'native marketplace lease and publication ownership rejects legacy loaded markers and changed bytes written after the new verifier publishes',
      ],
    },
    {
      file: 'src/server/services/meta/meta-sync-lease.sql.integration.test.ts',
      minimumAssertions: 16,
      requiredBehaviors: [
        'native Meta sync lease ownership uses separate disposable backends with the real bounded renewal function and restricted RLS role',
        'native Meta sync lease ownership rejects both partial-null lease states at the actual database constraint',
        'native Meta sync lease ownership allows exactly one winner when two connections claim the same queued job',
        'native Meta sync lease ownership advances generation on expiry takeover and rejects the old renewal while the new owner renews',
        'native Meta sync lease ownership rejects stale cursor counts and terminal state after a replacement owner claims',
        'native Meta sync lease ownership cancellation increments generation and rejects a late completion from the cancelled owner',
        'native Meta sync lease ownership denies cross-org job claims and mirror-effect reads under the actual app role',
        'native Meta sync lease ownership rolls back a domain write when row-lock waiting carries the transaction past lease expiry',
        'native Meta sync lease ownership fences a late domain publication after an expired generation is stolen',
        'native Meta sync lease ownership connection compare-and-swap preserves a user revocation and a competing token refresh',
        'native Meta sync lease ownership recovers a put response loss by reusing one active digest effect and publishing one file identity',
        'native Meta sync lease ownership creates immutable distinct keys when fetched bytes change and later revert to an old digest',
        'native Meta sync lease ownership binds the active effect pointer to the same organization platform and post',
        'native Meta sync lease ownership rechecks an absent cleanup tombstone and deletes a truly late put without touching a same-digest replacement',
        'native Meta sync lease ownership advances the cleanup schedule after a storage failure without claiming remote absence',
        'native Meta sync lease ownership orders the bounded cleanup queue fairly and never selects published effects',
      ],
    },
    {
      file: 'src/server/services/job-stock-concurrency.sql.integration.test.ts',
      minimumAssertions: 21,
      requiredBehaviors: [
        'identified disposable PostgreSQL safety requires explicit opt-in and rejects nonfixture URLs before connection',
        'identified disposable PostgreSQL safety rejects the explicitly provisioned unmarked database',
        'identified disposable PostgreSQL safety uses separate backends and a non-bypass stock role',
        'identified disposable PostgreSQL safety rejects injected fixture schema names before connection and preserves schema on idle reconnect',
        'native job ownership races rejects late owner done after another backend claims',
        'native job ownership races rejects late owner error after another backend claims',
        'native job ownership races rejects late owner progress after another backend claims',
        'native job ownership races cancellation wins over an in-flight progress result',
        'native job ownership races rechecks lease expiry after waiting for the ownership row lock',
        'native stock transaction races and connection loss rejects a concurrent draft edit after submission acquires the entry lock',
        'native stock transaction races and connection loss rejects a concurrent draft delete after submission acquires the entry lock',
        'native stock transaction races and connection loss two callers blocked on the actual invoice row converge on one posted entry',
        'native stock transaction races and connection loss tenant B cannot use tenant A invoice or stock rows',
        'native stock transaction races and connection loss resumes the committed draft from another backend without another entry',
        'native stock transaction races and connection loss survives post-ledger-commit response loss and retries on another backend',
        'native groupchat admission and message persistence commits run/job terminal atomically (orchestrator=false)',
        'native groupchat admission and message persistence commits run/job terminal atomically (orchestrator=true)',
        'native groupchat admission and message persistence replacement owner never repeats an admitted RPC or persists late output',
        'native groupchat admission and message persistence second job cannot duplicate a remote turn while first owner remains live',
        'native groupchat admission and message persistence committed message survives failed terminal finalization without another model call',
        'native groupchat admission and message persistence rejects a changed config after admission without persisting a different effect',
      ],
    },
    {
      file: 'src/server/services/job-effects.sql.integration.test.ts',
      minimumAssertions: 25,
      requiredBehaviors: [
        'native job receipt ownership binds one shared manifest across duplicate jobs and rejects incompatible progress',
        'native job receipt ownership rejects binding null manifest with existing admitted effects',
        'native job receipt ownership rejects binding null manifest with existing received effects',
        'native job receipt ownership rejects binding null manifest with existing committed effects',
        'native job receipt ownership requires manifest assertions on bound effect admission, replay and commit',
        'native job receipt ownership preserves the local completed guard exception without binding, admission or progress',
        'native job receipt ownership checks ready inside the locked missing-admission transaction but preserves existing indeterminacy',
        'native job receipt ownership preserves pinned provider/body after preparation and snapshots the caller contract',
        'native job receipt ownership reasserts manifest when a late provider response returns',
        'native job receipt ownership clears manifests on create, revoke and source-change revisions without deleting receipts',
        'native job receipt ownership the additive migration rejects malformed manifests and partial reapplication',
        'native job receipt ownership reuses a received batch after restart and atomically publishes only once',
        'native job receipt ownership duplicate jobs share admission while one request is in flight',
        'native job receipt ownership retains indeterminate admission after response loss and does not replay remotely',
        'native job receipt ownership rejects a late provider response after cancel',
        'native job receipt ownership rejects a late provider response after takeover',
        'native job receipt ownership rejects a late provider response after reset',
        'native job receipt ownership rolls back publication, receipt completion and progress together',
        'native job receipt ownership rejects a changed payload/configuration for an existing unit',
        'native job receipt ownership legacy adoption validates domain state once and refuses a later explicit request',
        'native job receipt ownership source jobs share semantic revisions and revoke old work after a changed source',
        'native job receipt ownership revocation plus domain deletion is atomic and stops old progress',
        'native job receipt ownership RLS denies cross-org receipts and cannot update bg_jobs; scope is restored for bookkeeping',
        'native job receipt ownership restores scope after an application error and preserves the original SQL error',
        'native job receipt ownership the authored migration rejects partial schemas and malformed persisted receipts',
      ],
    },
    {
      file: 'src/server/services/job-effect-pages.sql.integration.test.ts',
      minimumAssertions: 48,
      requiredBehaviors: [
        'native page effects and actual embedding transport packs changed units across documents and preserves per-page publication replay',
        'native page effects and actual embedding transport reuses B from a received A/B response while a new B/C page publishes independently',
        'native page effects and actual embedding transport rejects a changed full manifest even when required chunks are unchanged',
        'native page effects and actual embedding transport rolls back domain/page/progress together while preserving received results',
        'native page effects and actual embedding transport binds and publishes disabled without paid calls',
        'native page effects and actual embedding transport binds and publishes qdrant without paid calls',
        'native page effects and actual embedding transport pre-abort rejects before reservation and provider dispatch',
        'native overlap and retained historical evidence an ambiguous B overlap stops all new C reservations and outbound calls',
        'native overlap and retained historical evidence retains the complete original response after B supersession, then lets current A consume its index',
        'native overlap and retained historical evidence enforces four active transport calls for a full256-unit page',
        'native overlap and retained historical evidence uses current page identity for RLS and refuses another tenant handle',
        'native reservation recovery and structural SQL guards reuses an exact unsent reservation after the prior job is invalid, without repacking',
        'native reservation recovery and structural SQL guards yields for a live owner and preserves canonical cursor, units and reservation',
        'native reservation recovery and structural SQL guards returns owner_missing for an orphan without modifying any reservation',
        'native reservation recovery and structural SQL guards yields promptly when a foreign owner row is locked on a distinct connection',
        'native reservation recovery and structural SQL guards abandons every old companion placement and repacks only current A/C together',
        'native reservation recovery and structural SQL guards rolls back an incomplete companion release at outer commit after actor restoration',
        'native reservation recovery and structural SQL guards denies undeclared foreign recovery before touching a locked foreign owner',
        'native reservation recovery and structural SQL guards denies missing actor context and grants no direct job or actor-function authority',
        'native reservation recovery and structural SQL guards uses immediate actor context and restores it before returning from owned scope',
        'native stale actors and immutable received evidence retains no returned response after the original dispatch generation is replaced',
        'native stale actors and immutable received evidence rejects malformed or out-of-range actor generation ""',
        'native stale actors and immutable received evidence rejects malformed or out-of-range actor generation "0"',
        'native stale actors and immutable received evidence rejects malformed or out-of-range actor generation "-1"',
        'native stale actors and immutable received evidence rejects malformed or out-of-range actor generation "not-a-generation"',
        'native stale actors and immutable received evidence rejects malformed or out-of-range actor generation "2147483648"',
        'native stale actors and immutable received evidence rejects moving a received placement, replacing received values or mutating its descriptor',
        'native selected vector return ceiling conditions actual result return on 16777216 exact serialized bytes',
        'native selected vector return ceiling conditions actual result return on 16777217 exact serialized bytes',
        'native concurrent frontier and committed dispatch permits serializes simultaneous missing B and returns canonical busy for a changed frontier',
        'native concurrent frontier and committed dispatch permits never grants a dispatch permit when the actual admission COMMIT fails a deferred constraint',
        'native provider pinning and scoped reads refuses a changed provider before binding any page or head',
        'native provider pinning and scoped reads keeps the real private prepared endpoint after environment changes between reservation and dispatch',
        'native provider pinning and scoped reads leaves admission ambiguous after malformed short provider vectors',
        'native provider pinning and scoped reads leaves admission ambiguous after malformed wrong-count provider vectors',
        'native provider pinning and scoped reads uses actual escaped prepared JSON across documents without changing payload bytes',
        'native provider pinning and scoped reads filters unqualified page reads under the actual scoped role across tenants',
        'native complete foreign companion closure counts all 1024 companion units and heads before any recovery writes',
        'native complete foreign companion closure counts all 1025 companion units and heads before any recovery writes',
        'native persisted descriptor byte ceiling accepts exactly256KiB jsonb text and rolls back every head/page/cursor change one byte over',
        'native full foreign metadata capacity checks exactly 1048576 metadata bytes before recovery',
        'native full foreign metadata capacity checks exactly 1048577 metadata bytes before recovery',
        'native maximum owner frontier and independent head limit admits256 distinct historical batches and prelocks256 actual finished owner jobs',
        'native maximum owner frontier and independent head limit rejects1025 heads independently when unchanged page members expand a1024-unit companion closure',
        'native legacy and empty-page compatibility preserves an actual single-head receipt and requires recovery for its missing complete manifest',
        'native legacy and empty-page compatibility binds and publishes an empty page with recorded progress and no transport',
        'native immediate actor liveness rejects an expired same-generation actor before allowing a scoped unit statement',
        'native immediate actor liveness does not mistake a writable owner manifest for invalidation of a live foreign job',
      ],
    },
    {
      file: 'src/server/services/finance-statements.effect-ownership.sql.integration.test.ts',
      minimumAssertions: 41,
      requiredBehaviors: [
        'native statement ownership content-unique creation races return one committed import and one request',
        'native statement ownership creates, dedupes normalized content, and atomically commits parser output and progress',
        'native statement ownership serializes duplicate jobs without holding transactions open during file fetch',
        'native statement ownership fences a late file result after cancel',
        'native statement ownership fences a late file result after takeover',
        'native statement ownership fences a late file result after undo',
        'native statement ownership fences a late file result after retry',
        'native statement ownership undo then identical retry cannot let a queued first chunk resurrect the old request',
        'native statement ownership does not record a late file failure against an undone request',
        'native statement ownership rolls back accepted rows when the cursor update fails',
        'native statement ownership a committed chunk survives lost handler response and duplicate restart without another insert',
        'native statement ownership counts partial duplicate rows from actual inserts and preserves parser rejection semantics',
        'native statement ownership rejects legacy queued work and explicitly retries without deleting committed progress',
        'native statement ownership rejects legacy parsing work and explicitly retries without deleting committed progress',
        'native statement ownership persists a 500-row chunk with job progress and rejects parsing undo before explicit retry resumes',
        'native statement ownership RLS denies cross-org reads, parent references and writes without role leakage',
        'native statement ownership concurrent explicit retries retain only the last revision authority',
        'native statement ownership a retry waiting on the head cannot reset an import that completed after its pre-read',
        'native statement ownership failed content can be retried after storage recovery without resetting existing rows',
        "native parser version/provenance integration stale v1 'queued' cursor +0 preserves all domain effects",
        "native parser version/provenance integration stale v1 'queued' cursor 500 preserves all domain effects",
        "native parser version/provenance integration stale v1 'parsing' cursor +0 preserves all domain effects",
        "native parser version/provenance integration stale v1 'parsing' cursor 500 preserves all domain effects",
        "native parser version/provenance integration stale v2 'queued' cursor +0 preserves all domain effects",
        "native parser version/provenance integration stale v2 'queued' cursor 500 preserves all domain effects",
        "native parser version/provenance integration stale v2 'parsing' cursor +0 preserves all domain effects",
        "native parser version/provenance integration stale v2 'parsing' cursor 500 preserves all domain effects",
        'native parser version/provenance integration historical queued retry refuses before admission',
        'native parser version/provenance integration historical parsing retry refuses before admission',
        'native parser version/provenance integration historical failed retry refuses before admission',
        'native parser version/provenance integration historical undone retry refuses before admission',
        'native parser version/provenance integration a version change while retry waits rolls back head replacement and enqueue',
        'native parser version/provenance integration historical done returns persisted terminal outcome without parsing',
        'native parser version/provenance integration historical failed returns persisted terminal outcome without parsing',
        'native parser version/provenance integration raw CRLF source and decoded normalized provenance may differ without corrupting accounting',
        'native parser version/provenance integration raw BOM source and decoded normalized provenance may differ without corrupting accounting',
        'native parser version/provenance integration actual record-too-large header keeps fixed classification through persisted status route',
        'native parser version/provenance integration actual malformed-quoting header keeps fixed classification through persisted status route',
        'native parser version/provenance integration actual invalid-encoding header keeps fixed classification through persisted status route',
        'native parser version/provenance integration actual whole-input limit persists only fixed bounded classification',
        'native parser version/provenance integration late invalid-header result cannot fail a replaced request',
      ],
    },
    {
      file: 'src/server/services/brain-corpus.effect-ownership.sql.integration.test.ts',
      minimumAssertions: 13,
      requiredBehaviors: [
        'conversation corpus native effect ownership publishes a dirty conversation with receipts, health and exact progress in one owned commit',
        'conversation corpus native effect ownership legacy WhatsApp and current job types share one semantic admission for the same conversation',
        'conversation corpus native effect ownership dirty and reconcile scheduling of one conversation converge on one paid request and one revision',
        'conversation corpus native effect ownership a taken-over job cannot publish, change source health or advance after its response arrives',
        'conversation corpus native effect ownership cancellation between batches fences later admission and stops the second response',
        'conversation corpus native effect ownership a lost provider response leaves an admitted receipt; retries never pay again',
        'conversation corpus native effect ownership an older prepared snapshot never publishes over a newer source and re-prepares from the ledger',
        'conversation corpus native effect ownership a rollback between publication and progress keeps received vectors; the retry publishes without paying',
        'conversation corpus native effect ownership reconcile tombstones deleted conversations, keeps verified-empty sources healthy and commits the final cursor',
        'conversation corpus native effect ownership Qdrant-owned mode publishes canonical text without any embedding call and rejects a mismatched active generation',
        'conversation corpus native effect ownership tenant scoping holds under forced RLS and the restricted role never touches bg_jobs',
        'business corpus native effect ownership two business jobs share one admission, publish the sales domain once and reconcile deletions',
        'business corpus native effect ownership a stale business page cannot publish or advance over a record that changed after preparation',
      ],
    },
  ],
  attachments: [
    {
      file: 'src/server/services/attachments.authority.sql.integration.test.ts',
      minimumAssertions: 17,
      requiredBehaviors: [
        'native attachment authority RLS filters files and rejects a foreign lifecycle insert even without caller tenant predicates',
        'native attachment authority new lifecycle table denies provider browser roles even under permissive table defaults',
        'native attachment authority cannot read or claim a file in another tenant',
        'native attachment authority validates existence and tenant identity of every supported target type',
        'native attachment authority owner-scoped CRM access rejects non-owned and soft-deleted records',
        'native attachment authority a visible link allows the file but never exposes hidden cross-links',
        'native attachment authority uploader identity does not bypass linked-record module revocation',
        'native attachment authority unlinked upload requires uploader identity and a current module edit capability',
        'native attachment authority last unlink and typed intent retain module provenance against unrelated-module bypass',
        'native attachment authority unknown managed orphan is denied before and after migration classification, while own generic adoption remains possible',
        'native attachment authority actual proxy handler authorizes typed targets before reservation and storage and retains their module',
        'native attachment authority cannot claim another uploader generic file as an attachment or finalize it',
        'native attachment authority typed upload rejects missing targets before reserving or signing; actor/category are server owned',
        'native attachment authority durable classification survives last unlink and user-controlled category changes',
        'native attachment authority actual attachment, generic detail/raw/delete and finalize/link handlers deny the same hidden record',
        'native attachment authority actual claims-only tick resumes authorized deletion and never claims an active old orphan',
        'native attachment authority preserves generic-file visibility and avatar caching while attachment raw redirects are not cached',
      ],
    },
    {
      file: 'src/server/services/attachments.lifecycle.sql.integration.test.ts',
      minimumAssertions: 30,
      requiredBehaviors: [
        'native attachment deletion lifecycle rolls back failed claim admission before any object-store effect',
        'native attachment deletion lifecycle storage failure keeps a tombstone, blocks relink/read, and a new sweep resumes the same claim',
        'native attachment deletion lifecycle database cleanup failure after blob deletion retries without resurrecting the file or repeating physical deletion',
        'native attachment deletion lifecycle rejects reactivation and immutable key/tenant mutation on a pending claim',
        'native attachment deletion lifecycle failed claims rotate behind untouched work even when the sweep limit is one',
        'native attachment deletion lifecycle managed file keys cannot be overwritten after registration or deletion admission',
        'native attachment deletion lifecycle a link committed before sweeper acquires the file lock is never deleted',
        'native attachment deletion lifecycle a committed sweep claim prevents a concurrent linker before storage finishes',
        'native attachment deletion lifecycle concurrent retries delete one physical object and safely finish one committed claim',
        'native attachment deletion lifecycle record deletion commits before a waiting link, which then refuses the nonexistent record',
        'native attachment deletion lifecycle an admitted link serializes before record deletion; helper and trigger clean it idempotently',
        'native attachment deletion lifecycle CRM soft deletion cleans references while preserving durable file registration',
        'native attachment deletion lifecycle actual crm_contact DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual booking DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual event_type DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual product DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual stk_item DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual stk_entry DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual fin_invoice DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle actual pos_ticket DELETE trigger detaches only its tenant references with no storage effect',
        'native attachment deletion lifecycle unlink A then delete B retains both historical modules and refuses module removal',
        'native attachment deletion lifecycle owner maintenance cleanup preserves cross-tenant predicates and the captured append-only audit ACL',
        'native attachment deletion lifecycle a stale finalize HEAD cannot recreate a file after deletion',
        'native attachment deletion lifecycle defers live signed uploads and reconciles a late PUT after first deletion without forgetting the key',
        'native attachment deletion lifecycle migration backfill is idempotent and refuses cross-tenant legacy references',
        'native two-layer deletion (trash, then claim) unlink hides the link in the trash and restore moves it back with its original link identity',
        'native two-layer deletion (trash, then claim) a plain relink of a trashed file clears its trash row; restoring a link that is not trashed is refused',
        'native two-layer deletion (trash, then claim) the record DELETE trigger hides links as system-trashed rows that cannot be restored to the missing record',
        'native two-layer deletion (trash, then claim) the sweeper leaves a trashed file alone inside the retention window and claims it after',
        'native two-layer deletion (trash, then claim) re-hiding a restored link restarts its retention clock',
      ],
    },
  ],
  principal: [
    {
      file: 'src/server/auth/assistant-principal.sql.integration.test.ts',
      minimumAssertions: 8,
      requiredBehaviors: [
        'native assistant persisted assignment and revocation accepts current canonical/legacy gateway 30000000-0000-4000-8000-000000000001 through actual joins',
        'native assistant persisted assignment and revocation accepts current canonical/legacy gateway legacy-native through actual joins',
        'native assistant persisted assignment and revocation denies the next request after membership removal commits on another native connection',
        'native assistant persisted assignment and revocation denies the next request after assignment removal commits on another native connection',
        'native assistant persisted assignment and revocation denies a gateway moved to another organization despite cached owner capabilities',
        'native assistant persisted assignment and revocation denies ambiguous aliases and inactive persisted provisioning',
        'native assistant persisted assignment and revocation actual authorized override route commits through second connection and invalidates the warm real cache',
        'native assistant persisted assignment and revocation denies a nonmember override request before any native permission mutation',
      ],
    },
  ],
  'custom-properties': [
    {
      file: 'src/server/services/custom-properties.sql.integration.test.ts',
      minimumAssertions: 1,
      requiredBehaviors: [
        'custom properties PostgreSQL invariants enforces org RLS, CAS, explicit null, and config/value serialization',
      ],
    },
  ],
  formula: [
    {
      file: 'src/server/services/formula-sql.sql.integration.test.ts',
      minimumAssertions: 5,
      requiredBehaviors: [
        'formula compiler PostgreSQL semantics evaluates every scalar type with PostgreSQL numeric semantics',
        'formula compiler PostgreSQL semantics preserves lazy errors for CASE and COALESCE, including formula references',
        'formula compiler PostgreSQL semantics treats NULL divided by zero as blank and live division by zero as an error',
        'formula compiler PostgreSQL semantics executes nested boolean comparisons and binds hostile text as data',
        'formula compiler PostgreSQL semantics rejects adversarial expansion before sending SQL',
      ],
    },
    {
      file: 'src/server/services/formula-properties.sql.integration.test.ts',
      minimumAssertions: 3,
      requiredBehaviors: [
        'formula property PostgreSQL graph invariants persists, reorders, and evaluates V2 primaries before ordered auxiliaries',
        'formula property PostgreSQL graph invariants survives JSONB type round-trips and rejects cycles and archived dependencies',
        'formula property PostgreSQL graph invariants stores presentation under CAS while preserving formula AST and stale secondary references',
      ],
    },
  ],
  'qa-native': [
    {
      file: 'src/server/services/brain-business-corpus.sql.integration.test.ts',
      minimumAssertions: 1,
      requiredBehaviors: [
        'business corpus SQL against PostgreSQL EXPLAINs every payload and deletion-identity query against the live schema',
      ],
    },
    {
      file: 'src/server/services/brain-business-persistence.service.test.ts',
      minimumAssertions: 5,
      requiredBehaviors: [
        'business corpus set-based persistence bounds a 205-record page to document and chunk batches',
        'business corpus set-based persistence batches stale chunk deletion and returns the deleted count',
        'business corpus set-based persistence marks a changed document pending when its changed chunk has no vector',
        'business corpus set-based persistence skips fully unchanged items and deduplicates a repeated source identity',
        'business corpus persistence SQL against PostgreSQL EXPLAINs document, chunk, and stale-delete batches against the live schema',
      ],
    },
    {
      file: 'src/server/services/brains.effect-ownership.sql.integration.test.ts',
      minimumAssertions: 30,
      requiredBehaviors: [
        'brain ingestion native effect ownership creates a revision atomically with its document and job, then publishes real vectors and progress',
        'brain ingestion native effect ownership does not dispatch again after a response is lost before a durable receipt',
        'brain ingestion native effect ownership reingest while embedding is pending fences the old request and its returned vector',
        'brain ingestion native effect ownership fails a concurrent duplicate without repeating admission or poisoning the active original',
        'brain ingestion native effect ownership reuses all received batches after final publication rollback and keeps old chunks until commit',
        'brain ingestion native effect ownership cancellation aborts caller waiting when the provider ignores abort, without publishing its late response',
        'brain ingestion native effect ownership takeover cannot repeat an admitted call and the late previous owner cannot persist its response',
        'brain ingestion native effect ownership delete while embedding is pending revokes the request and does not resurrect the document',
        'brain ingestion native effect ownership rejects unversioned jobs before loading and explicit reingest provides a fresh bound recovery',
        'brain ingestion native effect ownership source mismatch is detected before provider work and cannot overwrite domain status',
        'brain ingestion native effect ownership a changed provider configuration cannot consume received vectors as a different request',
        'brain ingestion native effect ownership creation failure rolls back document, head and enqueue together without recording a success audit',
        'brain ingestion native effect ownership actual RLS denies cross-org reads and writes and a wrong brain cannot revoke a document request',
        'brain ingestion native effect ownership reingest during a blocked controlled URL fetch rejects old loaded content before embedding',
        'brain ingestion native effect ownership database constraints reject corrupt receipt vectors and valid received vectors remain reusable',
        'brain ingestion native effect ownership preserves empty embedding compatibility with revision-bound atomic publication',
        'brain ingestion native effect ownership preserves disabled embedding compatibility with revision-bound atomic publication',
        'brain ingestion native effect ownership canonicalizes database UUID identity before creating the source request',
        'brain ingestion native effect ownership ordinary controlled URL loading retains manual redirects and embeds the loaded text',
        'brain ingestion native effect ownership deletion during URL loading prevents admission after the load completes',
        'brain ingestion native effect ownership a delayed mutable module duplicate with a shared64-chunk prefix cannot admit extra batches after another job publishes',
        'brain ingestion native effect ownership an empty URL duplicate cannot publish over a different paid manifest already admitted',
        'brain ingestion native effect ownership a disabled duplicate cannot replace a bound embedded manifest while its provider is pending',
        'brain ingestion native effect ownership binds disabled publication before SQL rollback and rejects a later embedded plan',
        'brain ingestion native effect ownership binds empty publication before SQL rollback and rejects a later embedded plan',
        'brain ingestion native effect ownership rejects an ambiguous unbound receipt revision and explicit reingest recovers without removing its history',
        'brain ingestion native effect ownership a provider change between batches conflicts before another outbound request',
        'brain ingestion native effect ownership same-manifest duplicate retries finish with complete progress without new provider calls',
        'brain ingestion native effect ownership rejects a conflicting full module manifest before even its common-prefix batch can replay',
        'brain ingestion native effect ownership a delayed URL load failure after another duplicate publishes completes from canonical state',
      ],
    },
    {
      file: 'src/server/services/crm-journey.sql.integration.test.ts',
      minimumAssertions: 7,
      requiredBehaviors: [
        'deterministicMilestones deposit classification against PGlite absent config: the default "reserva" keyword classifies a deposit-only invoice as reserve/"Reserved a consult"',
        'deterministicMilestones deposit classification against PGlite absent config: a mixed invoice (procedure + deposit) is a purchase, labelled from the procedure item',
        'deterministicMilestones deposit classification against PGlite custom rule: "reserva" no longer matches, so the same line item becomes a purchase',
        'deterministicMilestones deposit classification against PGlite custom rule: a deposit-only invoice under the configured keyword uses the configured label',
        'deterministicMilestones deposit classification against PGlite malformed config: a non-object stored deposit value warns once and falls back to the default rule, same as absent config',
        'deterministicMilestones deposit classification against PGlite empty keywords: nothing is ever a deposit, so a non-null item always produces purchase, not reserve',
        'deterministicMilestones deposit classification against PGlite a same-tenant rule change is visible on the immediately next call: default → custom → empty → back to absent',
      ],
    },
    {
      file: 'src/server/services/tag-links.sql.integration.test.ts',
      minimumAssertions: 1,
      requiredBehaviors: [
        'tag link service SQL behavior scopes reads and replaces only manual links, including concurrent replacements',
      ],
    },
  ],
} as const satisfies Record<NativePostgresLane, readonly NativePostgresAdmission[]>;

export const NATIVE_POSTGRES_LANES = Object.freeze(
  Object.keys(NATIVE_POSTGRES_MANIFEST) as NativePostgresLane[],
);

export function nativePostgresAdmissions(lane: NativePostgresLane) {
  return NATIVE_POSTGRES_MANIFEST[lane] as readonly NativePostgresAdmission[];
}

export function nativePostgresFiles(lane: NativePostgresLane) {
  return nativePostgresAdmissions(lane).map(({ file }) => file);
}

export function isOrdinaryVitestNativeExclusion(file: string) {
  const normalized = file.replaceAll('\\', '/');
  return (
    normalized.endsWith('.sql.integration.test.ts') ||
    normalized === 'src/server/services/brain-business-persistence.service.test.ts' ||
    normalized === 'src/server/services/crm-funnel.concurrent.integration.test.ts'
  );
}
