/**
 * C4 model for the Minion meta-repo.
 *
 * This is deliberately source-backed rather than inferred at request time:
 * every internal node points at a checked path, route, or key template. The
 * local `architecture:recon` script hashes those artifacts into a gitignored
 * SQLite database so a later session can detect stale recon before changing
 * this model.
 */
export type C4Level = 'context' | 'container' | 'component' | 'code';
export type C4ReconStatus = 'verified' | 'partial' | 'external';
export type C4RelationKind = 'runtime' | 'data' | 'event' | 'deploy' | 'ownership';

export interface C4Node {
  id: string;
  name: string;
  level: C4Level;
  parentId: string | null;
  description: string;
  technology: string;
  icon: string;
  sourceRefs: string[];
  /** Concrete endpoints, directories, schemas, or storage key templates. */
  artefacts: string[];
  reconStatus: C4ReconStatus;
  /** Links live infrastructure health to the architecture node when possible. */
  statusNodeId?: string;
}

export interface C4Relation {
  source: string;
  target: string;
  label: string;
  technology: string;
  kind: C4RelationKind;
}

export interface C4Model {
  nodes: C4Node[];
  relations: C4Relation[];
  generatedFrom: string;
}

const node = (value: C4Node): C4Node => value;

export const C4_NODES: C4Node[] = [
  // Level 1 — System context.
  node({
    id: 'c4:minion',
    name: 'Minion Platform',
    level: 'context',
    parentId: null,
    description: 'Self-hosted personal AI assistant platform and its operational control plane.',
    technology: 'Software system',
    icon: 'Network',
    sourceRefs: ['AGENTS.md', 'specs/2026-04-19-minion-meta-repo-design.md'],
    artefacts: ['minion/', 'minion_hub/', 'minion_site/', 'paperclip-minion/', 'packages/'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:operator',
    name: 'Operators & Org Members',
    level: 'context',
    parentId: null,
    description:
      'People who configure agents, operate the business modules, and inspect reliability.',
    technology: 'Person',
    icon: 'Users',
    sourceRefs: ['minion_hub/src/routes/(app)/', 'minion_hub/src/server/services/rbac.service.ts'],
    artefacts: ['/reliability', '/workforce', '/crm', '/finances', '/settings'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:channel-platforms',
    name: 'Messaging Platforms',
    level: 'context',
    parentId: null,
    description: 'External chat networks used to receive and deliver agent conversations.',
    technology: 'External software systems',
    icon: 'MessageSquare',
    sourceRefs: ['minion/extensions/'],
    artefacts: ['WhatsApp WebSocket', 'Telegram Bot API', 'Discord API', 'Slack API'],
    reconStatus: 'external',
    statusNodeId: 'channel-apis',
  }),
  node({
    id: 'c4:business-systems',
    name: 'Business Data Systems',
    level: 'context',
    parentId: null,
    description: 'External fiscal, sales, advertising, and social data providers.',
    technology: 'External software systems',
    icon: 'Cloud',
    sourceRefs: [
      'minion_hub/src/server/services/finance.service.ts',
      'minion_hub/src/server/services/meta/meta-sync.service.ts',
    ],
    artefacts: ['SUSII HTTPS API', 'Meta Graph API'],
    reconStatus: 'partial',
  }),
  node({
    id: 'c4:delivery',
    name: 'Delivery & Edge',
    level: 'context',
    parentId: null,
    description: 'External hosting, routing, image distribution, and private-network services.',
    technology: 'External infrastructure systems',
    icon: 'Shield',
    sourceRefs: ['minion/deploy/swarm/stack.yml', 'minion_hub/vercel.json'],
    artefacts: ['Vercel', 'Cloudflare', 'Caddy', 'Tailscale', 'GHCR'],
    reconStatus: 'partial',
  }),

  // Level 2 — Containers.
  node({
    id: 'c4:gateway',
    name: 'Gateway Runtime',
    level: 'container',
    parentId: 'c4:minion',
    description:
      'Long-running WebSocket/HTTP runtime that owns agents, sessions, routing, and channels.',
    technology: 'Node.js 22 · TypeScript · pnpm',
    icon: 'Server',
    sourceRefs: [
      'minion/src/gateway/',
      'minion/src/agents/',
      'minion/src/channels/',
      'minion/extensions/',
    ],
    artefacts: ['wss /ws', 'tcp :18789 / :18790', '~/.minion/'],
    reconStatus: 'verified',
    statusNodeId: 'gateway-default',
  }),
  node({
    id: 'c4:hub',
    name: 'Minion Hub',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Multi-tenant operations dashboard, business suite, and gateway control API.',
    technology: 'SvelteKit 2 · Svelte 5 · Bun · Vercel',
    icon: 'Globe',
    sourceRefs: ['minion_hub/src/routes/', 'minion_hub/src/lib/', 'minion_hub/src/server/'],
    artefacts: ['https://hub.minion-ai.org', '/api/*'],
    reconStatus: 'verified',
    statusNodeId: 'hub',
  }),
  node({
    id: 'c4:site',
    name: 'Minion Site',
    level: 'container',
    parentId: 'c4:minion',
    description:
      'Marketing site and authenticated members experience with its own LibSQL-backed auth.',
    technology: 'SvelteKit 2 · Svelte 5 · Bun · Better Auth · Vercel',
    icon: 'Globe',
    sourceRefs: ['minion_site/src/routes/', 'minion_site/src/lib/'],
    artefacts: ['https://minion-ai.org', '/members'],
    reconStatus: 'verified',
    statusNodeId: 'site',
  }),
  node({
    id: 'c4:hub-desktop',
    name: 'Hub Desktop Shell',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Tauri desktop packaging with a local Node sidecar for the Hub application.',
    technology: 'Tauri 2 · Rust · Node sidecar',
    icon: 'Box',
    sourceRefs: ['minion_hub/src-tauri/', 'minion_hub/svelte.config.js'],
    artefacts: ['src-tauri/tauri.conf.json', 'src-tauri/src/lib.rs', 'adapter-node sidecar'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:paperclip',
    name: 'Workforce Control Plane',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Company, project, issue, and execution orchestration used by Workforce.',
    technology: 'Express · React/Vite · Drizzle · PGlite',
    icon: 'Boxes',
    sourceRefs: [
      'paperclip-minion/server/',
      'paperclip-minion/ui/',
      'paperclip-minion/packages/adapters/',
    ],
    artefacts: ['HTTP API :3100', 'adapter execution workspaces'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:shared',
    name: '@minion-stack Packages',
    level: 'container',
    parentId: 'c4:minion',
    description:
      'Protocol, database, auth, cache, UI, and tooling contracts shared across products.',
    technology: 'TypeScript packages · npm',
    icon: 'Package',
    sourceRefs: ['packages/'],
    artefacts: [
      '@minion-stack/shared',
      '@minion-stack/db',
      '@minion-stack/auth',
      '@minion-stack/cache',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:core-db',
    name: 'Core Postgres',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Canonical multi-tenant business and identity data store with row-level security.',
    technology: 'Supabase Postgres · Drizzle',
    icon: 'Database',
    sourceRefs: [
      'packages/db/src/',
      'minion_hub/src/server/db/pg-*.ts',
      'minion_hub/supabase/migrations/',
    ],
    artefacts: ['postgresql :5432 / pooler :6543', 'RLS org_id'],
    reconStatus: 'verified',
    statusNodeId: 'supabase-pg',
  }),
  node({
    id: 'c4:telemetry-db',
    name: 'Telemetry Store',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Gateway heartbeats, connection events, and legacy operational telemetry.',
    technology: 'Turso/libSQL · Drizzle',
    icon: 'Database',
    sourceRefs: ['minion_hub/src/server/db/schema/', 'minion_hub/src/server/db/client.ts'],
    artefacts: ['libsql wss :443', 'gateway_heartbeats', 'connection_events'],
    reconStatus: 'verified',
    statusNodeId: 'turso',
  }),
  node({
    id: 'c4:event-store',
    name: 'Gateway Event Store',
    level: 'container',
    parentId: 'c4:minion',
    description:
      'Canonical local reliability event log with write-behind synchronization to Turso.',
    technology: 'SQLite · write-behind sync',
    icon: 'Database',
    sourceRefs: ['minion/src/events/store.ts', 'minion/src/events/turso-sync.ts'],
    artefacts: ['<stateDir>/events.db', 'events', 'unified_events', 'gateway_heartbeats'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:site-db',
    name: 'Site Auth & Member Store',
    level: 'container',
    parentId: 'c4:minion',
    description: 'LibSQL database used by Site server data and Better Auth.',
    technology: 'Turso/libSQL · Drizzle · Better Auth',
    icon: 'Database',
    sourceRefs: ['minion_site/src/server/db/client.ts', 'minion_site/src/lib/auth/auth.ts'],
    artefacts: ['file:./data/minion_hub.db (local)', 'libsql://… (production)'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:blob',
    name: 'Object Storage',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Tenant-scoped uploaded files and mirrored media.',
    technology: 'Backblaze B2 · S3 API',
    icon: 'HardDrive',
    sourceRefs: [
      'minion_hub/src/server/storage/',
      'minion_hub/src/server/services/file.service.ts',
    ],
    artefacts: ['<orgId>/<category>/<fileId>/<fileName>'],
    reconStatus: 'verified',
    statusNodeId: 'b2',
  }),
  node({
    id: 'c4:cache',
    name: 'Coordination Cache',
    level: 'container',
    parentId: 'c4:minion',
    description: 'Ephemeral coordination and cache state shared by gateway and Hub services.',
    technology: 'Valkey · Redis protocol',
    icon: 'Zap',
    sourceRefs: ['packages/cache/', 'minion/deploy/swarm/stack.yml'],
    artefacts: [
      'redis://valkey:6379',
      '<namespace>:v<version>:<domain>[:t=<tenant>][:u=<user>][:sorted dimensions]',
    ],
    reconStatus: 'partial',
    statusNodeId: 'valkey',
  }),

  // Level 3 — Components.
  node({
    id: 'c4:gateway:http',
    name: 'Gateway HTTP/WS Server',
    level: 'component',
    parentId: 'c4:gateway',
    description: 'Accepts HTTP requests, WS upgrades, authentication, and gateway methods.',
    technology: 'Node HTTP · ws · JSON frame protocol',
    icon: 'Network',
    sourceRefs: ['minion/src/gateway/server.impl.ts', 'minion/src/gateway/server/'],
    artefacts: ['/ws', 'req | res | event frames', 'connect.challenge → connect'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:protocol-auth',
    name: 'Protocol, Methods & Authorization',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Advertises the stable RPC/event contract and enforces session, role, scope, and assigned-agent boundaries.',
    technology: 'JSON frames · Zod · operator scopes',
    icon: 'Shield',
    sourceRefs: [
      'minion/src/gateway/server-core/server-methods-list.ts',
      'minion/src/gateway/server-core/server-methods.ts',
      'minion/src/gateway/protocol/',
    ],
    artefacts: [
      '159 base gateway methods',
      '39 gateway events',
      'operator.admin | operator.read | operator.write',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:agent-runtime',
    name: 'Agent Execution Pipeline',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Resolves recipients and sessions, assembles prompts/tools, runs the embedded agent, and dispatches replies.',
    technology: 'Pi embedded runner · TypeScript services',
    icon: 'GitBranch',
    sourceRefs: [
      'minion/src/agents/pi-embedded/pi-embedded-runner.ts',
      'minion/src/auto-reply/reply/',
      'minion/src/dispatch/',
      'minion/src/routing/',
    ],
    artefacts: ['inbound message → session → prompt/tools → model stream → outbound reply'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:channels',
    name: 'Channel Extensions',
    level: 'component',
    parentId: 'c4:gateway',
    description: 'Provider adapters normalize inbound/outbound messages into the gateway pipeline.',
    technology: 'Extension packages',
    icon: 'MessageSquare',
    sourceRefs: [
      'minion/src/channels/',
      'minion/extensions/whatsapp/',
      'minion/extensions/telegram/',
      'minion/extensions/discord/',
    ],
    artefacts: ['extensions/<channel>/', 'normalized channel events'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:sessions',
    name: 'Sessions, Transcripts & Workspaces',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Persists agent session metadata, JSONL transcripts, workspaces, configuration, and guarded filesystem paths.',
    technology: 'Filesystem · JSON · JSONL',
    icon: 'HardDrive',
    sourceRefs: ['minion/src/config/sessions/', 'minion/src/config/paths.ts', 'minion/src/agents/'],
    artefacts: [
      '<state>/agents/<agentId>/sessions/sessions.json',
      '<sessionId>[-topic-<topicId>].jsonl',
      '<state>/agents/<agentId>/workspace',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:plugins-tools',
    name: 'Plugins, Tools & MCP',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Loads plugins, registers tools and hooks, and exposes MCP discovery, invocation, OAuth, and reconciliation.',
    technology: 'Plugin runtime · MCP 2025-06-18',
    icon: 'Plug',
    sourceRefs: [
      'minion/src/plugins/',
      'minion/src/gateway/mcp/',
      'minion/src/agents/tool-governance/',
    ],
    artefacts: [
      'plugin loader → runtime registry',
      'tools/list',
      'tools/call',
      '/.well-known/oauth-*',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:memory',
    name: 'Memory Search & Consolidation',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Indexes workspace memory, performs FTS/vector hybrid search, and supplies snapshots to agent runs.',
    technology: 'SQLite FTS5 · sqlite-vec · embeddings',
    icon: 'Brain',
    sourceRefs: [
      'minion/src/memory/',
      'minion/src/gateway/server-methods/memory.ts',
      'minion/src/gateway/server-methods/dream-history.ts',
    ],
    artefacts: ['memory.snapshot', 'dream.history', 'FTS5 + vector result fusion'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:automation',
    name: 'Automation & Remote Work',
    level: 'component',
    parentId: 'c4:gateway',
    description: 'Schedules cron jobs and executes flows, drones, and long-lived remote shells.',
    technology: 'Cron service · flow triggers · exe.dev bridge',
    icon: 'Clock',
    sourceRefs: [
      'minion/src/platform/cron/',
      'minion/src/flows/',
      'minion/src/drones/',
      'minion/src/shells/',
    ],
    artefacts: ['cron.*', 'flows/<flowId>', 'drone pipeline', 'shells.*'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:nodes-devices',
    name: 'Nodes, Devices & Pairing',
    level: 'component',
    parentId: 'c4:gateway',
    description:
      'Pairs operator devices and remote nodes, rotates credentials, and invokes node-host capabilities.',
    technology: 'Pairing stores · node-host runner · gateway RPC',
    icon: 'Monitor',
    sourceRefs: [
      'minion/src/pairing/',
      'minion/src/node-host/',
      'minion/src/gateway/server-methods/nodes.ts',
    ],
    artefacts: ['node.pair.*', 'device.pair.*', 'node.invoke', '<oauth>/<channel>-pairing.json'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:gateway:reliability',
    name: 'Reliability RPC & Heartbeat',
    level: 'component',
    parentId: 'c4:gateway',
    description: 'Serves reliability RPCs, emits canonical events, and pushes heartbeat evidence.',
    technology: 'Gateway methods · SQLite events',
    icon: 'Activity',
    sourceRefs: [
      'minion/src/gateway/server-methods/reliability.ts',
      'minion/src/gateway/server.impl.ts',
      'minion/src/events/',
    ],
    artefacts: [
      'reliability.events',
      'reliability.summary',
      'reliability.timeline',
      'reliability.flow',
      'reliability.usage',
      'reliability.activity',
      'reliability.perf',
      'reliability.plugins',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:reliability',
    name: 'Reliability Architecture',
    level: 'component',
    parentId: 'c4:hub',
    description: 'Live probes plus topology and code-backed C4 exploration.',
    technology: 'Svelte 5 · PixiJS · SvelteKit API',
    icon: 'Activity',
    sourceRefs: [
      'minion_hub/src/lib/components/reliability/architecture/',
      'minion_hub/src/server/services/architecture.service.ts',
      'minion_hub/src/routes/api/reliability/architecture/+server.ts',
    ],
    artefacts: ['/reliability?tab=architecture', 'GET /api/reliability/architecture'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:gateway-bridge',
    name: 'Gateway Bridge',
    level: 'component',
    parentId: 'c4:hub',
    description: 'Connects the UI to gateway frames and exposes scoped query/action endpoints.',
    technology: '@minion-stack/shared WS client · Svelte state',
    icon: 'Radio',
    sourceRefs: [
      'minion_hub/src/lib/services/gateway.svelte.ts',
      'minion_hub/src/routes/api/gateway/',
    ],
    artefacts: ['wss /ws', '/api/gateway/query/*', '/api/gateway/actions/*'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:app-shell',
    name: 'Application Shell & Domain State',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Bootstraps the authenticated application, navigation, feature state, and live gateway-backed client stores.',
    technology: 'Svelte 5 runes · SvelteKit layouts',
    icon: 'LayoutDashboard',
    sourceRefs: [
      'minion_hub/src/routes/(app)/+layout.svelte',
      'minion_hub/src/routes/(app)/+layout.server.ts',
      'minion_hub/src/lib/state/',
    ],
    artefacts: ['(app)/+layout.server.ts → (app)/+layout.svelte', 'src/lib/state/<domain>/'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:crm-knowledge',
    name: 'CRM & Knowledge Corpus',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Joins contacts, parties, channel identities, conversations, finance context, embeddings, and focused brains.',
    technology: 'SvelteKit handlers · Drizzle · pgvector/FTS',
    icon: 'Brain',
    sourceRefs: [
      'minion_hub/src/server/services/crm-contacts.service.ts',
      'minion_hub/src/server/services/brain-corpus.service.ts',
      'minion_hub/src/routes/api/crm/',
      'minion_hub/src/routes/api/brains/',
    ],
    artefacts: [
      '41 CRM handlers',
      '22 brain handlers',
      'Master Brain',
      'All Conversations focused brain',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:commerce',
    name: 'Finance, POS & Stock',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Reconciles fiscal data, posts POS tickets, explodes recipe consumption, and maintains stock entries, bins, and ledgers.',
    technology: 'SvelteKit handlers · Drizzle transactions',
    icon: 'Boxes',
    sourceRefs: [
      'minion_hub/src/server/services/finance.service.ts',
      'minion_hub/src/server/services/pos.service.ts',
      'minion_hub/src/server/services/stock.service.ts',
    ],
    artefacts: [
      '18 finance handlers',
      '14 POS handlers',
      '27 stock handlers',
      'invoice → issue → ledger',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:operations',
    name: 'Scheduling, Socials & Support',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Runs resources, availability, bookings, reminders, social synchronization, and customer support cases.',
    technology: 'SvelteKit handlers · domain services',
    icon: 'Calendar',
    sourceRefs: [
      'minion_hub/src/server/services/scheduling.service.ts',
      'minion_hub/src/server/services/support.service.ts',
      'minion_hub/src/routes/api/meta/',
    ],
    artefacts: ['28 scheduling handlers', '13 Meta handlers', '6 support handlers'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:workforce',
    name: 'Workforce Control-Plane Adapter',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Maps signed Hub identities and factory-intake requests onto the Paperclip Workforce control plane.',
    technology: 'SvelteKit proxy · signed identity · Paperclip HTTP API',
    icon: 'Workflow',
    sourceRefs: [
      'minion_hub/src/lib/server/workforce-fetch.ts',
      'minion_hub/src/routes/api/workforce/',
      'minion_hub/src/lib/workforce/',
    ],
    artefacts: [
      '8 /api/workforce handlers',
      '/api/workforce/<path...>',
      '/api/workforce/factory-intake',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:data-access',
    name: 'Org-Scoped Data Access',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Owns Postgres pools, transaction recovery, Drizzle schemas, and per-transaction organization context.',
    technology: 'PostgreSQL · Drizzle · RLS',
    icon: 'Database',
    sourceRefs: [
      'minion_hub/src/server/db/pg-pool.ts',
      'minion_hub/src/server/db/pg-client.ts',
      'minion_hub/src/server/db/with-org-core.ts',
    ],
    artefacts: [
      'SET LOCAL role/GUC',
      "set_config('app.current_org_id', <orgId>, true)",
      'pg_* tables',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:auth',
    name: 'Identity, Org Context & RBAC',
    level: 'component',
    parentId: 'c4:hub',
    description:
      'Resolves Supabase identity, active organization, capabilities, row and field scope.',
    technology: 'Supabase GoTrue · PostgreSQL RLS · RBAC',
    icon: 'Shield',
    sourceRefs: [
      'minion_hub/src/hooks.server.ts',
      'minion_hub/src/server/auth/',
      'minion_hub/src/server/services/rbac.service.ts',
    ],
    artefacts: ['session cookie', 'Bearer server token', '<module>:<action>'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:jobs',
    name: 'Scheduled Jobs',
    level: 'component',
    parentId: 'c4:hub',
    description: 'Idempotent tick endpoints reconcile business, reliability, and knowledge state.',
    technology: 'Vercel/host cron · SvelteKit handlers',
    icon: 'Clock',
    sourceRefs: [
      'minion_hub/src/lib/automations/system-automations.ts',
      'minion_hub/src/routes/api/jobs/tick/+server.ts',
    ],
    artefacts: ['/api/jobs/tick', '/api/brains/reconcile/tick', '/api/reliability/retention/tick'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub-desktop:runtime',
    name: 'Desktop Runtime Bridge',
    level: 'component',
    parentId: 'c4:hub-desktop',
    description: 'Bootstraps the local sidecar and exposes the packaged Hub web runtime.',
    technology: 'Rust commands · Tauri process plugin',
    icon: 'Box',
    sourceRefs: ['minion_hub/src-tauri/src/lib.rs', 'minion_hub/src-tauri/tauri.conf.json'],
    artefacts: ['sidecar process', 'desktop app window'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:hub:files',
    name: 'File Service',
    level: 'component',
    parentId: 'c4:hub',
    description: 'Stores metadata in Postgres and bytes in the S3-compatible blob driver.',
    technology: 'Drizzle · AWS S3 SDK',
    icon: 'File',
    sourceRefs: [
      'minion_hub/src/server/services/file.service.ts',
      'minion_hub/src/server/storage/',
    ],
    artefacts: ['GET/POST /api/files', 'GET/DELETE /api/files/<id>', 'GET /api/files/<id>/raw'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:site:marketing',
    name: 'Marketing Experience',
    level: 'component',
    parentId: 'c4:site',
    description: 'Prerendered public product, privacy, and terms pages.',
    technology: 'SvelteKit prerender',
    icon: 'Globe',
    sourceRefs: ['minion_site/src/routes/(marketing)/'],
    artefacts: ['/', '/privacy', '/terms'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:site:members',
    name: 'Members Experience',
    level: 'component',
    parentId: 'c4:site',
    description: 'Authenticated member dashboard using the shared auth and gateway contracts.',
    technology: 'SvelteKit · Better Auth',
    icon: 'Users',
    sourceRefs: ['minion_site/src/routes/(app)/', 'minion_site/src/lib/auth/'],
    artefacts: ['/login', '/register', '/members'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:paperclip:server',
    name: 'Orchestration Server',
    level: 'component',
    parentId: 'c4:paperclip',
    description: 'REST API and services for companies, agents, projects, issues, and runs.',
    technology: 'Express · Drizzle',
    icon: 'Server',
    sourceRefs: ['paperclip-minion/server/'],
    artefacts: ['REST API', 'orchestration services'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:paperclip:adapters',
    name: 'Agent Adapters',
    level: 'component',
    parentId: 'c4:paperclip',
    description: 'Execution adapters for Claude, Codex, Cursor, and Minion gateway workers.',
    technology: 'TypeScript packages',
    icon: 'Plug',
    sourceRefs: ['paperclip-minion/packages/adapters/'],
    artefacts: ['packages/adapters/<runtime>/', 'execution workspace'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:shared:protocol',
    name: 'Gateway Protocol Contract',
    level: 'component',
    parentId: 'c4:shared',
    description: 'Frames, agent/session/chat types, and the shared WebSocket client.',
    technology: '@minion-stack/shared',
    icon: 'Braces',
    sourceRefs: ['packages/shared/src/'],
    artefacts: ['req', 'res', 'event', 'connect.challenge'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:shared:data',
    name: 'Data & Auth Contracts',
    level: 'component',
    parentId: 'c4:shared',
    description:
      'Canonical database schema and Better Auth factory package; auth is currently consumed by Site.',
    technology: '@minion-stack/db · @minion-stack/auth',
    icon: 'Database',
    sourceRefs: ['packages/db/src/', 'packages/auth/src/'],
    artefacts: ['Drizzle schemas', 'createAuth()'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:core-db:domains',
    name: 'Org Domain Schemas',
    level: 'component',
    parentId: 'c4:core-db',
    description: 'Org-scoped operational tables protected by RLS and service-layer context.',
    technology: 'Postgres schemas · migrations',
    icon: 'Table',
    sourceRefs: ['minion_hub/src/server/db/pg-*.ts', 'minion_hub/supabase/migrations/'],
    artefacts: ['organizations', 'profiles', 'crm_*', 'fin_*', 'stock_*', 'sched_*'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:site-db:auth',
    name: 'Site Database & Auth Adapter',
    level: 'component',
    parentId: 'c4:site-db',
    description: 'Creates the LibSQL client and binds Better Auth to the Drizzle adapter.',
    technology: '@libsql/client · Drizzle adapter',
    icon: 'Database',
    sourceRefs: ['minion_site/src/server/db/client.ts', 'minion_site/src/lib/auth/auth.ts'],
    artefacts: ['getDb()', 'createAuth()', 'file:./data/minion_hub.db'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:telemetry-db:metrics',
    name: 'Operational Metrics Schema',
    level: 'component',
    parentId: 'c4:telemetry-db',
    description: 'Append-oriented status evidence used by Reliability views and probes.',
    technology: 'SQLite/libSQL tables',
    icon: 'Activity',
    sourceRefs: [
      'minion_hub/src/server/db/schema/gateway-heartbeats.ts',
      'minion_hub/src/server/db/schema/connection-events.ts',
    ],
    artefacts: ['gateway_heartbeats', 'connection_events', 'skill_stats'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:event-store:sync',
    name: 'Local Event Log & Turso Sync',
    level: 'component',
    parentId: 'c4:event-store',
    description:
      'Appends canonical events locally and flushes batches to remote operational tables.',
    technology: 'SQLite · libSQL sync worker',
    icon: 'Activity',
    sourceRefs: ['minion/src/events/store.ts', 'minion/src/events/turso-sync.ts'],
    artefacts: ['events', 'unified_events', 'gateway_heartbeats'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:blob:s3',
    name: 'S3 Blob Driver',
    level: 'component',
    parentId: 'c4:blob',
    description: 'Provider-neutral put, signed-get, and delete operations over Backblaze B2.',
    technology: 'AWS S3 SDK',
    icon: 'HardDrive',
    sourceRefs: [
      'minion_hub/src/server/storage/blob.ts',
      'minion_hub/src/server/storage/drivers/s3.ts',
    ],
    artefacts: ['put(key)', 'getSignedUrl(key)', 'delete(key)'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:cache:namespaces',
    name: 'Cache Key Namespace',
    level: 'component',
    parentId: 'c4:cache',
    description: 'Deterministic tenant/domain keys and invalidation tags.',
    technology: '@minion-stack/cache',
    icon: 'Key',
    sourceRefs: ['packages/cache/src/'],
    artefacts: [
      '<namespace>:v<version>:<domain>[:t=<tenant>][:u=<user>][:sorted dimensions]',
      'c:<logicalKey>',
      'tag:<tag>',
      'kt:<logicalKey>',
    ],
    reconStatus: 'partial',
  }),

  // Level 4 — Code and concrete contracts.
  node({
    id: 'c4:code:gateway-server',
    name: 'server.impl.ts',
    level: 'code',
    parentId: 'c4:gateway:http',
    description:
      'Gateway server assembly, HTTP routes, WS upgrades, authentication, and method dispatch.',
    technology: 'TypeScript module',
    icon: 'FileCode',
    sourceRefs: ['minion/src/gateway/server.impl.ts', 'minion/src/gateway/server/'],
    artefacts: ['GET/upgrade /ws', 'connect.challenge', 'tools/call'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:gateway-contract',
    name: 'BASE_METHODS + GATEWAY_EVENTS',
    level: 'code',
    parentId: 'c4:gateway:protocol-auth',
    description:
      'Indexed gateway capability floor and the authorization dispatcher that maps methods onto handlers and scopes.',
    technology: 'TypeScript const contracts',
    icon: 'Braces',
    sourceRefs: [
      'minion/src/gateway/server-core/server-methods-list.ts',
      'minion/src/gateway/server-core/server-methods.ts',
    ],
    artefacts: [
      'BASE_METHODS[159]',
      'GATEWAY_EVENTS[39]',
      'coreGatewayHandlers',
      'operator.* scopes',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:agent-execution',
    name: 'Embedded Agent Run Pipeline',
    level: 'code',
    parentId: 'c4:gateway:agent-runtime',
    description:
      'Concrete runner, reply execution, dispatch, prompt assembly, and tool-policy modules used by each agent turn.',
    technology: 'TypeScript modules',
    icon: 'FileCode',
    sourceRefs: [
      'minion/src/agents/pi-embedded/pi-embedded-runner.ts',
      'minion/src/auto-reply/reply/agent-runner-execution.ts',
      'minion/src/auto-reply/reply/reply-dispatcher.ts',
      'minion/src/agents/system-prompt/system-prompt.ts',
    ],
    artefacts: [
      'runEmbeddedPiAgent()',
      'runAgentExecution()',
      'dispatchReply()',
      'buildAgentSystemPrompt()',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:channel-slugs',
    name: 'extensions/<channel>/',
    level: 'code',
    parentId: 'c4:gateway:channels',
    description: 'Provider-specific adapters loaded as channel extensions.',
    technology: 'pnpm workspace packages',
    icon: 'FolderCode',
    sourceRefs: [
      'minion/extensions/whatsapp/',
      'minion/extensions/telegram/',
      'minion/extensions/discord/',
    ],
    artefacts: [
      'extensions/whatsapp',
      'extensions/telegram',
      'extensions/discord',
      'extensions/slack',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:workspace-template',
    name: 'Agent Workspace Template',
    level: 'code',
    parentId: 'c4:gateway:sessions',
    description: 'Filesystem contract for per-agent durable workspaces.',
    technology: 'Directory/key template',
    icon: 'FolderCode',
    sourceRefs: [
      'minion_hub/src/server/services/personal-agent-provisioner.ts',
      'minion/src/config/',
    ],
    artefacts: ['<state>/agents/<agentId>/workspace', '<state>/minion.json'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:session-paths',
    name: 'Session Store & Transcript Paths',
    level: 'code',
    parentId: 'c4:gateway:sessions',
    description:
      'Validated path constructors and stores for agent session metadata and append-only transcript files.',
    technology: 'TypeScript · JSON · JSONL',
    icon: 'Key',
    sourceRefs: [
      'minion/src/config/sessions/paths.ts',
      'minion/src/config/sessions/store.ts',
      'minion/src/config/sessions/transcript.ts',
    ],
    artefacts: [
      '<state>/agents/<agentId>/sessions/sessions.json',
      '<state>/agents/<agentId>/sessions/<sessionId>.jsonl',
      '<sessionId>-topic-<topicId>.jsonl',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:plugin-mcp-runtime',
    name: 'Plugin + MCP Registries',
    level: 'code',
    parentId: 'c4:gateway:plugins-tools',
    description:
      'Loads plugin manifests/runtime hooks, registers tools, and reconciles the HTTP MCP surface.',
    technology: 'TypeScript registries · MCP HTTP',
    icon: 'Plug',
    sourceRefs: [
      'minion/src/plugins/loader.ts',
      'minion/src/plugins/tool-registry.ts',
      'minion/src/plugins/runtime/index.ts',
      'minion/src/gateway/mcp/mcp-http.ts',
      'minion/src/gateway/mcp/registry.ts',
    ],
    artefacts: [
      'loadPlugins()',
      'createPluginRuntime()',
      'tools/list',
      'tools/call',
      'MCP protocol 2025-06-18',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:memory-index',
    name: 'SQLite Hybrid Memory Index',
    level: 'code',
    parentId: 'c4:gateway:memory',
    description:
      'SQLite-backed indexing manager with FTS, embedding batches, vector search, and atomic reindex behavior.',
    technology: 'node:sqlite · sqlite-vec',
    icon: 'Database',
    sourceRefs: [
      'minion/src/memory/manager.ts',
      'minion/src/memory/sqlite.ts',
      'minion/src/memory/sqlite-vec.ts',
      'minion/src/memory/index.ts',
    ],
    artefacts: [
      'memory index SQLite',
      'FTS5 rows',
      'vector rows',
      'workspace file hash → chunk records',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:automation-stores',
    name: 'Cron, Flow, Drone & Shell Runtime',
    level: 'code',
    parentId: 'c4:gateway:automation',
    description:
      'Persistent cron scheduling plus flow triggers, drone pipelines, shell provisioning, bridge RPC, and backups.',
    technology: 'JSON store · WebSocket bridge · exe.dev',
    icon: 'Workflow',
    sourceRefs: [
      'minion/src/platform/cron/service.ts',
      'minion/src/platform/cron/store.ts',
      'minion/src/flows/trigger-manager.ts',
      'minion/src/drones/pipeline.ts',
      'minion/src/shells/manager.ts',
      'minion/src/shells/store.ts',
    ],
    artefacts: [
      '<config>/cron/jobs.json',
      'CronService',
      'FlowTriggerManager',
      'drone pipeline',
      'shells JSON state',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:node-pairing',
    name: 'Pairing Stores + Node Host',
    level: 'code',
    parentId: 'c4:gateway:nodes-devices',
    description:
      'Hashed pairing codes and allowlists guard node/device enrollment before the node-host runner accepts invocations.',
    technology: 'Atomic JSON · SHA-256 · process runner',
    icon: 'Key',
    sourceRefs: [
      'minion/src/pairing/pairing-store.ts',
      'minion/src/pairing/token-hash.ts',
      'minion/src/node-host/runner.ts',
      'minion/src/node-host/invoke-browser.ts',
    ],
    artefacts: [
      '<oauth>/<channel>-pairing.json',
      '<oauth>/<channel>[-<account>]-allowFrom.json',
      'node.invoke',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:reliability-rpc',
    name: 'Gateway Reliability Methods',
    level: 'code',
    parentId: 'c4:gateway:reliability',
    description: 'Concrete gateway RPC handlers and their cache/version boundaries.',
    technology: 'TypeScript method handlers',
    icon: 'Network',
    sourceRefs: [
      'minion/src/gateway/server-methods/reliability.ts',
      'minion/src/gateway/server-methods/plugins-health.ts',
    ],
    artefacts: [
      'reliability.events',
      'reliability.summary',
      'reliability.timeline',
      'reliability.flow',
      'reliability.usage',
      'reliability.activity',
      'reliability.perf',
      'reliability.plugins',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:arch-api',
    name: 'GET /api/reliability/architecture',
    level: 'code',
    parentId: 'c4:hub:reliability',
    description:
      'RBAC-gated live snapshot containing probes, deployment topology, and the C4 model.',
    technology: 'SvelteKit RequestHandler',
    icon: 'Route',
    sourceRefs: ['minion_hub/src/routes/api/reliability/architecture/+server.ts'],
    artefacts: ['GET /api/reliability/architecture', 'reliability:view'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:arch-service',
    name: 'architecture.service.ts',
    level: 'code',
    parentId: 'c4:hub:reliability',
    description: 'Static deployment topology plus concurrent direct and derived health probes.',
    technology: 'TypeScript service',
    icon: 'FileCode',
    sourceRefs: ['minion_hub/src/server/services/architecture.service.ts'],
    artefacts: ['probeArchitecture()', 'ARCH_NODES', 'ARCH_EDGES'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:arch-ui',
    name: 'ArchitectureGraph.svelte',
    level: 'code',
    parentId: 'c4:hub:reliability',
    description: 'Pixi graph orchestration, C4 depth controls, focus rings, and detail inspection.',
    technology: 'Svelte 5 component',
    icon: 'FileCode',
    sourceRefs: ['minion_hub/src/lib/components/reliability/architecture/ArchitectureGraph.svelte'],
    artefacts: ['context → container → component → code filters', 'node focus rings'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:reliability-http',
    name: 'Reliability HTTP Endpoints',
    level: 'code',
    parentId: 'c4:hub:reliability',
    description:
      'Concrete Hub handlers that read architecture, insights, events, credentials, heartbeats, and skill health.',
    technology: 'SvelteKit RequestHandlers',
    icon: 'Network',
    sourceRefs: ['minion_hub/src/routes/api/reliability/', 'minion_hub/src/routes/api/metrics/'],
    artefacts: [
      'GET /api/reliability/architecture',
      'GET /api/reliability/insights',
      'GET /api/reliability/retention/tick',
      'GET /api/metrics/connection-events',
      'GET/POST /api/metrics/credential-health',
      'GET /api/metrics/gateway-heartbeats',
      'GET/POST /api/metrics/skill-stats',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:gateway-query',
    name: '/api/gateway/query/*',
    level: 'code',
    parentId: 'c4:hub:gateway-bridge',
    description: 'Read-only org-scoped endpoints exposed to gateway tools.',
    technology: 'SvelteKit route family',
    icon: 'Route',
    sourceRefs: ['minion_hub/src/routes/api/gateway/query/'],
    artefacts: [
      'GET /api/gateway/query/finance',
      'GET /api/gateway/query/stock',
      'GET /api/gateway/query/bookings',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:gateway-actions',
    name: '/api/gateway/actions/*',
    level: 'code',
    parentId: 'c4:hub:gateway-bridge',
    description: 'Capability-gated mutation endpoints used by agent tools.',
    technology: 'SvelteKit route family',
    icon: 'Route',
    sourceRefs: ['minion_hub/src/routes/api/gateway/actions/'],
    artefacts: [
      'POST /api/gateway/actions/pos-sale',
      'POST /api/gateway/actions/stock-entry-create',
      'POST /api/gateway/actions/ticket-create',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:app-shell',
    name: '(app) Layout + State Modules',
    level: 'code',
    parentId: 'c4:hub:app-shell',
    description:
      'Server layout resolves identity/org/module state before the Svelte shell initializes navigation and domain stores.',
    technology: 'SvelteKit layout · Svelte 5 runes',
    icon: 'LayoutDashboard',
    sourceRefs: [
      'minion_hub/src/routes/(app)/+layout.server.ts',
      'minion_hub/src/routes/(app)/+layout.svelte',
      'minion_hub/src/lib/state/index.ts',
    ],
    artefacts: ['load() → AppLayoutData', 'Topbar + Sidebar + route slot', 'state/<domain>/'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:crm-corpus',
    name: 'CRM + Conversation Corpus',
    level: 'code',
    parentId: 'c4:hub:crm-knowledge',
    description:
      'Concrete contact/party relationship services and all-channel normalization, source discovery, indexing, and hybrid retrieval.',
    technology: 'TypeScript services · Drizzle SQL',
    icon: 'Brain',
    sourceRefs: [
      'minion_hub/src/server/services/crm-contacts.service.ts',
      'minion_hub/src/server/services/crm-relationship.service.ts',
      'minion_hub/src/server/services/brain-corpus.service.ts',
      'minion_hub/src/server/services/brain-hybrid-retrieval.service.ts',
    ],
    artefacts: [
      'GET/POST /api/crm/contacts',
      'POST /api/brains/<id>/search',
      'conversation:<channel>:<account>:<conversationId>',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:commerce-services',
    name: 'Finance · POS · Stock Services',
    level: 'code',
    parentId: 'c4:hub:commerce',
    description:
      'Domain services and route families for fiscal sync, ticket posting, recipe expansion, stock entries, bins, and ledgers.',
    technology: 'TypeScript services · Postgres transactions',
    icon: 'FolderCode',
    sourceRefs: [
      'minion_hub/src/server/services/finance.service.ts',
      'minion_hub/src/server/services/pos.service.ts',
      'minion_hub/src/server/services/stock.service.ts',
      'minion_hub/src/routes/api/finances/',
      'minion_hub/src/routes/api/pos/',
      'minion_hub/src/routes/api/stock/',
    ],
    artefacts: [
      'POST /api/finances/sync',
      'POST /api/pos/tickets',
      'POST /api/stock/entries',
      'qtyConsumption × unitsPerStockUom',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:operations-services',
    name: 'Scheduling · Meta · Support Routes',
    level: 'code',
    parentId: 'c4:hub:operations',
    description:
      'Route and service implementations for availability/bookings, Meta sync and attribution, and support issue workflows.',
    technology: 'SvelteKit RequestHandlers · services',
    icon: 'Route',
    sourceRefs: [
      'minion_hub/src/server/services/scheduling.service.ts',
      'minion_hub/src/server/services/support.service.ts',
      'minion_hub/src/routes/api/scheduling/',
      'minion_hub/src/routes/api/meta/',
      'minion_hub/src/routes/api/support/',
    ],
    artefacts: ['GET/POST /api/scheduling/bookings', '/api/meta/*', 'GET/POST /api/support'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:workforce-proxy',
    name: '/api/workforce/<path...>',
    level: 'code',
    parentId: 'c4:hub:workforce',
    description:
      'Catch-all authenticated proxy and bounded factory-intake route preserve signed actor identity and mutation origin.',
    technology: 'SvelteKit RequestHandlers · HTTP proxy',
    icon: 'Route',
    sourceRefs: [
      'minion_hub/src/routes/api/workforce/[...path]/+server.ts',
      'minion_hub/src/routes/api/workforce/factory-intake/+server.ts',
      'minion_hub/src/lib/server/workforce-fetch.ts',
    ],
    artefacts: [
      'GET/POST/PATCH/PUT/DELETE /api/workforce/<path...>',
      'POST /api/workforce/factory-intake',
      'x-hub-identity | Bearer pcli_*',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:org-data-context',
    name: 'Postgres Pool + Org Transaction Context',
    level: 'code',
    parentId: 'c4:hub:data-access',
    description:
      'Separates general, critical, and RLS pools and binds organization identity to the transaction-local database context.',
    technology: 'Drizzle · postgres.js · PostgreSQL RLS',
    icon: 'FolderCode',
    sourceRefs: [
      'minion_hub/src/server/db/pg-pool.ts',
      'minion_hub/src/server/db/pg-client.ts',
      'minion_hub/src/server/db/with-org-core.ts',
      'minion_hub/src/server/db/pg-ledger-client.ts',
    ],
    artefacts: [
      'getPgClient()',
      'getCriticalPgClient()',
      'getRlsPgClient()',
      "set_config('app.current_org_id', <orgId>, true)",
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:hooks-rbac',
    name: 'hooks.server.ts + rbac.service.ts',
    level: 'code',
    parentId: 'c4:hub:auth',
    description: 'Canonical request identity resolution and module/action capability checks.',
    technology: 'SvelteKit hook · TypeScript service',
    icon: 'FileCode',
    sourceRefs: [
      'minion_hub/src/hooks.server.ts',
      'minion_hub/src/server/services/rbac.service.ts',
    ],
    artefacts: [
      'requireOrgCapability(<module>, <action>)',
      'ownerFilter()',
      'shouldMaskSensitive()',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:desktop-sidecar',
    name: 'src-tauri runtime files',
    level: 'code',
    parentId: 'c4:hub-desktop:runtime',
    description: 'Concrete Tauri configuration and Rust sidecar lifecycle implementation.',
    technology: 'Rust + JSON configuration',
    icon: 'Box',
    sourceRefs: ['minion_hub/src-tauri/src/lib.rs', 'minion_hub/src-tauri/tauri.conf.json'],
    artefacts: ['src-tauri/src/lib.rs', 'src-tauri/tauri.conf.json'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:tick-routes',
    name: 'Tick Endpoint Registry',
    level: 'code',
    parentId: 'c4:hub:jobs',
    description: 'Source-of-truth list of cadence and execution wiring for scheduled endpoints.',
    technology: 'TypeScript registry',
    icon: 'FileCode',
    sourceRefs: ['minion_hub/src/lib/automations/system-automations.ts'],
    artefacts: [
      '/api/jobs/tick',
      '/api/finances/sync/tick',
      '/api/meta/sync/tick',
      '/api/brains/reconcile/tick',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:file-endpoints',
    name: 'File API Endpoints',
    level: 'code',
    parentId: 'c4:hub:files',
    description:
      'Org-scoped metadata, upload, signed download, raw download, and deletion handlers.',
    technology: 'SvelteKit RequestHandlers',
    icon: 'Route',
    sourceRefs: ['minion_hub/src/routes/api/files/'],
    artefacts: ['GET/POST /api/files', 'GET/DELETE /api/files/<id>', 'GET /api/files/<id>/raw'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:site-routes',
    name: '(marketing)/ route group',
    level: 'code',
    parentId: 'c4:site:marketing',
    description: 'Concrete public route group and prerender boundaries.',
    technology: 'SvelteKit route group',
    icon: 'FolderCode',
    sourceRefs: ['minion_site/src/routes/(marketing)/'],
    artefacts: ['src/routes/(marketing)/'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:member-routes',
    name: '(app)/members routes',
    level: 'code',
    parentId: 'c4:site:members',
    description: 'Authenticated members route group and shared auth client.',
    technology: 'SvelteKit route group',
    icon: 'FolderCode',
    sourceRefs: ['minion_site/src/routes/(app)/', 'minion_site/src/lib/auth/'],
    artefacts: ['src/routes/(app)/members', 'createAuth()'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:paperclip-server',
    name: 'server/ orchestration services',
    level: 'code',
    parentId: 'c4:paperclip:server',
    description: 'Express route and service implementation for control-plane resources.',
    technology: 'TypeScript directory',
    icon: 'FolderCode',
    sourceRefs: ['paperclip-minion/server/'],
    artefacts: ['server/routes/', 'server/services/'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:adapter-packages',
    name: 'packages/adapters/<runtime>/',
    level: 'code',
    parentId: 'c4:paperclip:adapters',
    description: 'Runtime-specific process launch, workspace, and result collection contracts.',
    technology: 'pnpm workspace packages',
    icon: 'FolderCode',
    sourceRefs: ['paperclip-minion/packages/adapters/'],
    artefacts: ['claude', 'codex', 'cursor', 'minion_gateway'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:shared-protocol',
    name: 'packages/shared/src/',
    level: 'code',
    parentId: 'c4:shared:protocol',
    description: 'Published frame types, domain types, utilities, and WebSocket client.',
    technology: 'TypeScript package source',
    icon: 'FolderCode',
    sourceRefs: ['packages/shared/src/'],
    artefacts: ['GatewayFrame', 'GatewayWsClient', 'agent/session/chat event types'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:db-auth-packages',
    name: 'packages/db + packages/auth',
    level: 'code',
    parentId: 'c4:shared:data',
    description: 'Published schema/migration runner and shared Better Auth factory.',
    technology: 'TypeScript package source',
    icon: 'FolderCode',
    sourceRefs: ['packages/db/src/', 'packages/auth/src/'],
    artefacts: ['@minion-stack/db/schema', 'createAuth()'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:site-db-auth',
    name: 'Site LibSQL/Auth Modules',
    level: 'code',
    parentId: 'c4:site-db:auth',
    description: 'Concrete Site database client and Better Auth configuration.',
    technology: 'TypeScript modules',
    icon: 'Database',
    sourceRefs: ['minion_site/src/server/db/client.ts', 'minion_site/src/lib/auth/auth.ts'],
    artefacts: ['src/server/db/client.ts', 'src/lib/auth/auth.ts'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:domain-schemas',
    name: 'pg-<domain>-schema.ts',
    level: 'code',
    parentId: 'c4:core-db:domains',
    description: 'Hub-side domain schema modules and SQL migrations.',
    technology: 'Drizzle schema files',
    icon: 'FolderCode',
    sourceRefs: ['minion_hub/src/server/db/', 'minion_hub/supabase/migrations/'],
    artefacts: [
      'pg-crm-schema.ts',
      'pg-finance-schema.ts',
      'pg-stock-schema.ts',
      'pg-scheduling-schema.ts',
    ],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:telemetry-schemas',
    name: 'Telemetry table modules',
    level: 'code',
    parentId: 'c4:telemetry-db:metrics',
    description: 'Concrete table declarations read by architecture probes and Reliability panels.',
    technology: 'Drizzle SQLite schemas',
    icon: 'FolderCode',
    sourceRefs: ['minion_hub/src/server/db/schema/'],
    artefacts: ['gateway-heartbeats.ts', 'connection-events.ts', 'skill-stats.ts'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:event-store',
    name: 'events/store.ts + turso-sync.ts',
    level: 'code',
    parentId: 'c4:event-store:sync',
    description: 'Concrete local schema and remote write-behind implementation.',
    technology: 'TypeScript modules',
    icon: 'Database',
    sourceRefs: ['minion/src/events/store.ts', 'minion/src/events/turso-sync.ts'],
    artefacts: ['<stateDir>/events.db', 'events', 'unified_events', 'gateway_heartbeats'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:b2-key',
    name: 'B2 Object Key Template',
    level: 'code',
    parentId: 'c4:blob:s3',
    description: 'Deterministic tenant boundary for every uploaded object.',
    technology: 'Storage slug template',
    icon: 'Key',
    sourceRefs: ['minion_hub/src/server/services/file.service.ts'],
    artefacts: ['<orgId>/<category>/<fileId>/<fileName>'],
    reconStatus: 'verified',
  }),
  node({
    id: 'c4:code:cache-key',
    name: 'Cache Key Templates',
    level: 'code',
    parentId: 'c4:cache:namespaces',
    description:
      'Tenant/domain cache keys and invalidation tags emitted by the shared cache package.',
    technology: 'String key templates',
    icon: 'Key',
    sourceRefs: ['packages/cache/src/'],
    artefacts: [
      '<namespace>:v<version>:<domain>[:t=<tenant>][:u=<user>][:sorted dimensions]',
      'c:<logicalKey>',
      'tag:<tag>',
      'kt:<logicalKey>',
    ],
    reconStatus: 'partial',
  }),
];

export const C4_RELATIONS: C4Relation[] = [
  {
    source: 'c4:operator',
    target: 'c4:hub',
    label: 'operates',
    technology: 'HTTPS :443',
    kind: 'runtime',
  },
  {
    source: 'c4:operator',
    target: 'c4:site',
    label: 'visits / signs in',
    technology: 'HTTPS :443',
    kind: 'runtime',
  },
  {
    source: 'c4:hub',
    target: 'c4:gateway',
    label: 'controls and streams',
    technology: 'WSS /ws',
    kind: 'runtime',
  },
  {
    source: 'c4:site',
    target: 'c4:gateway',
    label: 'members assistant',
    technology: 'WSS /ws',
    kind: 'runtime',
  },
  {
    source: 'c4:gateway',
    target: 'c4:channel-platforms',
    label: 'receives and sends messages',
    technology: 'WS + HTTPS',
    kind: 'event',
  },
  {
    source: 'c4:hub',
    target: 'c4:business-systems',
    label: 'reconciles external records',
    technology: 'HTTPS jobs',
    kind: 'event',
  },
  {
    source: 'c4:hub',
    target: 'c4:core-db',
    label: 'reads and writes org data',
    technology: 'Postgres pooler :6543',
    kind: 'data',
  },
  {
    source: 'c4:site',
    target: 'c4:site-db',
    label: 'stores identity and member data',
    technology: 'LibSQL',
    kind: 'data',
  },
  {
    source: 'c4:hub',
    target: 'c4:telemetry-db',
    label: 'reads operational evidence',
    technology: 'libSQL WSS',
    kind: 'data',
  },
  {
    source: 'c4:hub',
    target: 'c4:blob',
    label: 'stores uploaded bytes',
    technology: 'S3 HTTPS',
    kind: 'data',
  },
  {
    source: 'c4:gateway',
    target: 'c4:cache',
    label: 'coordinates workers',
    technology: 'Redis :6379',
    kind: 'data',
  },
  {
    source: 'c4:gateway',
    target: 'c4:event-store',
    label: 'appends reliability events',
    technology: 'SQLite',
    kind: 'event',
  },
  {
    source: 'c4:event-store',
    target: 'c4:telemetry-db',
    label: 'write-behind synchronization',
    technology: 'libSQL batches',
    kind: 'event',
  },
  {
    source: 'c4:hub',
    target: 'c4:paperclip',
    label: 'projects and executions',
    technology: 'HTTP API',
    kind: 'runtime',
  },
  {
    source: 'c4:shared',
    target: 'c4:hub',
    label: 'provides contracts',
    technology: 'npm package',
    kind: 'ownership',
  },
  {
    source: 'c4:shared',
    target: 'c4:site',
    label: 'provides contracts',
    technology: 'npm package',
    kind: 'ownership',
  },
  {
    source: 'c4:shared',
    target: 'c4:paperclip',
    label: 'provides WS client',
    technology: 'npm package',
    kind: 'ownership',
  },
  {
    source: 'c4:delivery',
    target: 'c4:gateway',
    label: 'routes and deploys',
    technology: 'Cloudflare/Caddy/GHCR',
    kind: 'deploy',
  },
  { source: 'c4:delivery', target: 'c4:hub', label: 'hosts', technology: 'Vercel', kind: 'deploy' },
  {
    source: 'c4:delivery',
    target: 'c4:site',
    label: 'hosts',
    technology: 'Vercel',
    kind: 'deploy',
  },
  {
    source: 'c4:hub:gateway-bridge',
    target: 'c4:gateway:http',
    label: 'sends gateway frames',
    technology: '@minion-stack/shared',
    kind: 'runtime',
  },
  {
    source: 'c4:gateway:http',
    target: 'c4:gateway:protocol-auth',
    label: 'authenticates and dispatches methods',
    technology: 'JSON frames + scopes',
    kind: 'runtime',
  },
  {
    source: 'c4:gateway:channels',
    target: 'c4:gateway:agent-runtime',
    label: 'publishes normalized messages',
    technology: 'internal events',
    kind: 'event',
  },
  {
    source: 'c4:gateway:agent-runtime',
    target: 'c4:gateway:sessions',
    label: 'loads session and transcript state',
    technology: 'JSON + JSONL',
    kind: 'data',
  },
  {
    source: 'c4:gateway:agent-runtime',
    target: 'c4:gateway:plugins-tools',
    label: 'selects and invokes governed tools',
    technology: 'plugin runtime + MCP',
    kind: 'runtime',
  },
  {
    source: 'c4:gateway:agent-runtime',
    target: 'c4:gateway:memory',
    label: 'retrieves memory context',
    technology: 'FTS5 + vector search',
    kind: 'data',
  },
  {
    source: 'c4:gateway:automation',
    target: 'c4:gateway:agent-runtime',
    label: 'starts scheduled and remote work',
    technology: 'cron/flow/drone triggers',
    kind: 'event',
  },
  {
    source: 'c4:gateway:nodes-devices',
    target: 'c4:gateway:automation',
    label: 'hosts remote shell and node execution',
    technology: 'node.invoke + bridge WS',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:reliability',
    target: 'c4:gateway:http',
    label: 'probes WS upgrade',
    technology: 'WSS',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:reliability',
    target: 'c4:gateway:reliability',
    label: 'queries reliability methods',
    technology: 'gateway RPC',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:app-shell',
    target: 'c4:hub:gateway-bridge',
    label: 'subscribes to live gateway state',
    technology: 'Svelte runes',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:auth',
    target: 'c4:hub:data-access',
    label: 'binds org and capability context',
    technology: 'request locals + RLS',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:crm-knowledge',
    target: 'c4:hub:data-access',
    label: 'joins parties, messages, and vectors',
    technology: 'Drizzle SQL',
    kind: 'data',
  },
  {
    source: 'c4:hub:commerce',
    target: 'c4:hub:data-access',
    label: 'posts transactional records',
    technology: 'Postgres transactions',
    kind: 'data',
  },
  {
    source: 'c4:hub:operations',
    target: 'c4:hub:data-access',
    label: 'persists bookings and cases',
    technology: 'Drizzle SQL',
    kind: 'data',
  },
  {
    source: 'c4:hub:jobs',
    target: 'c4:hub:crm-knowledge',
    label: 'reconciles corpus and relationships',
    technology: 'tick handlers',
    kind: 'event',
  },
  {
    source: 'c4:hub:jobs',
    target: 'c4:hub:commerce',
    label: 'runs fiscal and stock reconciliation',
    technology: 'tick handlers',
    kind: 'event',
  },
  {
    source: 'c4:hub:jobs',
    target: 'c4:hub:operations',
    label: 'runs reminders and external sync',
    technology: 'tick handlers',
    kind: 'event',
  },
  {
    source: 'c4:hub:workforce',
    target: 'c4:paperclip:server',
    label: 'proxies signed control-plane requests',
    technology: 'HTTPS + signed identity',
    kind: 'runtime',
  },
  {
    source: 'c4:hub:data-access',
    target: 'c4:core-db:domains',
    label: 'executes org-scoped queries',
    technology: 'Postgres RLS',
    kind: 'data',
  },
  {
    source: 'c4:hub:files',
    target: 'c4:blob:s3',
    label: 'puts and signs objects',
    technology: 'S3 SDK',
    kind: 'data',
  },
  {
    source: 'c4:shared:protocol',
    target: 'c4:hub:gateway-bridge',
    label: 'defines frame/client contract',
    technology: 'TypeScript',
    kind: 'ownership',
  },
  {
    source: 'c4:shared:data',
    target: 'c4:core-db:domains',
    label: 'defines canonical schemas',
    technology: 'Drizzle',
    kind: 'ownership',
  },
  {
    source: 'c4:telemetry-db:metrics',
    target: 'c4:hub:reliability',
    label: 'supplies heartbeats and events',
    technology: 'libSQL queries',
    kind: 'data',
  },
];

export const C4_MODEL: C4Model = {
  nodes: C4_NODES,
  relations: C4_RELATIONS,
  generatedFrom: 'source-backed model + gitignored minion_hub/.architecture-recon/index.sqlite',
};
